"""`ReportModel` -> a self-contained, print-ready HTML document.

Follows the same three print-CSS principles xFormat's own HTML export uses
(`apps/web/src/features/cv/cvHtmlTemplate.ts` in the `xformat` checkout,
read for the pattern only — it is a TypeScript/React template, nothing from
it is imported here):

* `@page { size: A4; margin: 0; }` — no page margin. `body`'s own background
  is the page's background (see the light palette below), and this document
  reads as a printed page with a tinted ground, not a white sheet with a
  card floating on it — a physical margin around that ground would put a
  band of plain white between the paper's edge and the tint, which looks
  like a mistake, not a design. The gutter readers actually need is around
  the *text*, not the page, so it lives as horizontal-only padding on
  `body` (`CONTENT_PADDING_H_MM`) — inline, not block: a heading or a
  finding card may sit close to the top or bottom of a page (that boundary
  is already handled by where things break, see below), but never flush
  against the left or right edge of the tint.
* Page breaks governed by what must stay together, not by what looks tidy.
  `break-inside: avoid` on every finding card was the obvious rule and the
  wrong one: a tall card that did not fit in the remainder of a page moved to
  the next page whole, and the space it left behind stayed blank — on a report
  of any size, a third of many pages. What actually has to hold is narrower —
  a heading is never the last thing on a page (`break-after: avoid`), a stray
  line never opens or closes one (`orphans`/`widows`), and small blocks (a
  field, a table row, a chart bar) stay whole. Cards and tables may break.
* mm/pt units throughout — a print document, not a screen one.

Colours and type come from `ui.tokens.Palette`, always the **light** theme:
the report is meant to be printed or read as a document, and a dark card on
white paper is illegible on a real printer — see `render_html`'s `lang`
default and the light-only choice below.
"""
from __future__ import annotations

import base64
import html
from pathlib import Path

from audit.base import ADVISORY, EXACT, NEEDS_BROWSER
from report.markup import (
    ROLE_LABELS, ROLES, highlight, role_css, role_of, roles_used,
)
from report.model import CATEGORY_AI_TEXT, ReportModel
from ui.tokens import Palette, palettes

#: Vendored alongside the app icon — see `ui/main_window.py`'s `ASSETS`.
#: Reading it from here rather than reaching into a sibling `xformat`
#: checkout (which may not exist on the machine building the report) keeps
#: the report generator, like the desktop app itself, buildable from this
#: repository alone.
_LOGO_PATH = Path(__file__).resolve().parent.parent / "ui" / "design" / "assets" / "logo-light.svg"

#: Horizontal-only gutter around text, in millimetres - see the `@page`
#: note above. `report.pdf` deliberately does *not* read this: the page
#: itself stays margin-0 (the tint bleeds to the physical edge), and this
#: number only ever becomes CSS padding on `body`.
CONTENT_PADDING_H_MM = 18

#: Minimal, self-contained labels for the report's own chrome. Not routed
#: through `i18n.translations.t()`: this package does not touch that module
#: (see the repository's task boundary), and a report has a small, fixed
#: vocabulary of its own rather than the UI's much larger one.
_LABELS = {
    "en": dict(
        title="Scan report", generated="Generated", target="Target",
        summary="Summary", by_severity="By severity", by_category="By category",
        findings="Findings", no_findings="No findings — nothing to report.",
        category="Category", count="Count", found="Found", why="Why it matters",
        fix="How to fix", replacement="Ready replacement", engine="Detected by",
        wcag="WCAG", footer="Generated by AI Content Scanner.",
        owner="{platform} markup", agreement="{count} engines",
        pages_examined="Pages examined", ai_patterns="AI-generated text patterns",
        typography="Typography issues (non-keyboard characters)",
        confidence="Confidence", text="Text", explanation="Explanation",
        character="Character", score="Score",
        overview="Overview", what_found="What was found", kind="Kind",
        legend="Element colours", elem_col="Element", no_element="page-level",
        certainty="Certainty", cert={"exact": "settled", "advisory": "editorial",
            "needs-browser": "needs a browser"},
        found_markup="Markup as found", fix_markup="Markup as it should be",
        source_group="Where it comes from", detail="Detail",
        chart_severity="By severity", chart_category="By category",
        where_work="Where the work is", top_problems="Most repeated problems",
        top_places="Pages with the most findings",
        pages_more="and {count} more pages", page_col="Page or file",
        top_patterns="Highest-scoring passages",
        found_in="Found in {count} places", and_more="and {count} more",
        occurrences="Occurrences",
        source_at="Source: {path}:{line}",
        repo_coverage="Matched to the given repository: {matched}/{total} passages",
        mode={"text-web": "AI-text scan · website", "text-repo": "AI-text scan · repository",
             "audit-web": "Site audit · website", "audit-repo": "Site audit · repository",
             "audit-file": "Site audit · page"},
        cat={"ai-text": "AI-sounding text", "accessibility": "Accessibility",
            "performance": "Performance", "seo": "SEO", "geo": "GEO readiness", "best-practices": "Best practices",
            "security": "Security"},
    ),
    "uk": dict(
        title="Звіт сканування", generated="Створено", target="Ціль",
        summary="Зведення", by_severity="За тяжкістю", by_category="За категорією",
        findings="Знахідки", no_findings="Знахідок немає — звітувати нема про що.",
        category="Категорія", count="Кількість", found="Що знайдено", why="Чому це важливо",
        fix="Як виправити", replacement="Готова заміна", engine="Знайшов",
        wcag="WCAG", footer="Згенеровано AI Content Scanner.",
        owner="розмітка {platform}", agreement="рушіїв: {count}",
        pages_examined="Переглянуті сторінки", ai_patterns="AI-згенеровані текстові патерни",
        typography="Проблеми типографіки (символи без клавіатури)",
        confidence="Впевненість", text="Текст", explanation="Пояснення",
        character="Символ", score="Оцінка",
        overview="Огляд", what_found="Що знайдено", kind="Вид",
        legend="Кольори елементів", elem_col="Елемент", no_element="рівень сторінки",
        certainty="Певність", cert={"exact": "доведено", "advisory": "редакційне",
            "needs-browser": "потрібен браузер"},
        found_markup="Розмітка як є", fix_markup="Розмітка як має бути",
        source_group="Звідки", detail="Деталь",
        chart_severity="За тяжкістю", chart_category="За категорією",
        where_work="Де робота", top_problems="Що повторюється найчастіше",
        top_places="Сторінки з найбільшою кількістю знахідок",
        pages_more="і ще {count} сторінок", page_col="Сторінка або файл",
        top_patterns="Уривки з найвищою оцінкою",
        found_in="Знайдено у {count} місцях", and_more="і ще {count}",
        occurrences="Повторів",
        source_at="Джерело: {path}:{line}",
        repo_coverage="Знайдено в репозиторії: {matched}/{total} уривків",
        mode={"text-web": "Аналіз тексту · сайт", "text-repo": "Аналіз тексту · репозиторій",
             "audit-web": "Аудит доступності · сайт", "audit-repo": "Аудит доступності · репозиторій",
             "audit-file": "Аудит доступності · сторінка"},
        cat={"ai-text": "Схоже на текст ШІ", "accessibility": "Доступність",
            "performance": "Продуктивність", "seo": "SEO", "geo": "GEO-готовність", "best-practices": "Найкращі практики",
            "security": "Безпека"},
    ),
    "it": dict(
        title="Report di scansione", generated="Generato", target="Destinazione",
        summary="Riepilogo", by_severity="Per gravità", by_category="Per categoria",
        findings="Rilievi", no_findings="Nessun rilievo: niente da segnalare.",
        category="Categoria", count="Conteggio", found="Cosa è stato trovato",
        why="Perché è importante", fix="Come correggere", replacement="Sostituzione pronta",
        engine="Rilevato da", wcag="WCAG", footer="Generato da AI Content Scanner.",
        owner="markup di {platform}", agreement="motori: {count}",
        pages_examined="Pagine esaminate", ai_patterns="Pattern di testo generati da AI",
        typography="Problemi di tipografia (caratteri non da tastiera)",
        confidence="Confidenza", text="Testo", explanation="Spiegazione",
        character="Carattere", score="Punteggio",
        overview="Panoramica", what_found="Che cosa è stato trovato", kind="Tipo",
        legend="Colori degli elementi", elem_col="Elemento", no_element="livello pagina",
        certainty="Certezza", cert={"exact": "accertato", "advisory": "editoriale",
            "needs-browser": "serve il browser"},
        found_markup="Markup come trovato", fix_markup="Markup come dovrebbe essere",
        source_group="Da dove viene", detail="Dettaglio",
        chart_severity="Per gravità", chart_category="Per categoria",
        where_work="Dove sta il lavoro", top_problems="I problemi più ripetuti",
        top_places="Pagine con più rilievi",
        pages_more="e altre {count} pagine", page_col="Pagina o file",
        top_patterns="Passaggi con punteggio più alto",
        found_in="Trovato in {count} punti", and_more="e altri {count}",
        occurrences="Occorrenze",
        source_at="Origine: {path}:{line}",
        repo_coverage="Corrispondenza nel repository indicato: {matched}/{total} passaggi",
        mode={"text-web": "Analisi testo · sito", "text-repo": "Analisi testo · repository",
             "audit-web": "Audit di accessibilità · sito",
             "audit-repo": "Audit di accessibilità · repository",
             "audit-file": "Audit di accessibilità · pagina"},
        cat={"ai-text": "Testo dall'aspetto artificiale", "accessibility": "Accessibilità",
            "performance": "Prestazioni", "seo": "SEO", "geo": "Prontezza GEO", "best-practices": "Best practice",
            "security": "Sicurezza"},
    ),
}

#: One CSS class per rank so a mixed report (there is no such run today, but
#: nothing stops one) still paints consistently: rank 0-3, clamped, covers
#: both severity vocabularies (see `report.model.SEVERITY_RANK`).
_SEVERITY_LABEL = {
    0: {"en": "Critical", "uk": "Критично", "it": "Critico"},
    1: {"en": "Serious", "uk": "Серйозно", "it": "Grave"},
    2: {"en": "Moderate", "uk": "Помірно", "it": "Moderato"},
    3: {"en": "Minor", "uk": "Незначно", "it": "Minore"},
}


def _labels(lang: str) -> dict:
    return _LABELS.get(lang, _LABELS["en"])


def _logo_data_uri() -> str:
    try:
        raw = _LOGO_PATH.read_bytes()
    except OSError:
        return ""
    encoded = base64.b64encode(raw).decode("ascii")
    return f"data:image/svg+xml;base64,{encoded}"


def _esc(value) -> str:
    """Escape anything interpolated into the document. Applied even to
    fields that are normally plain prose (a rule's `why`/`fix` text can
    still carry a raw `<` or `&` when it quotes an attribute value or a
    URL), and always to `snippet`/`replacement`, which are markup or code
    shown *as text* — never rendered as markup, per the task's escaping
    requirement."""
    return html.escape(str(value or ""), quote=True)


#: The four-step ramp, as fills. The same four tokens the window's severity
#: bar and the TUI's summary table paint with, so one severity is one colour
#: across every surface this product has.
def _severity_inks(palette: Palette) -> dict:
    return {0: palette.sev_critical, 1: palette.sev_high,
            2: palette.sev_medium, 3: palette.sev_none}


def _severity_css(palette: Palette) -> str:
    """The severity *badge* only.

    It used to also paint the article, because the badge and the card carried
    the same class - so every finding sat on a tinted panel and a page of
    forty findings was a wash of red and amber with the actual content
    floating in it. The panel is neutral now (see `.finding`); this inks one
    small rectangle and the words on it.
    """
    rules = []
    for rank, fill in _severity_inks(palette).items():
        ink = palette.on_amber if rank in (2, 3) else palette.on_error
        rules.append(f".badge.sev-{rank} {{ color: {ink}; background: {fill}; }}")
    return "\n".join(rules)


def _rule_css(palette: Palette) -> str:
    """The rank as a rule down the left edge of the panel - the one place a
    finding's severity is allowed to colour anything larger than a badge."""
    return "\n".join(
        f".finding.rule-{rank} {{ border-left: 1.2mm solid {fill}; }}"
        for rank, fill in _severity_inks(palette).items())


def _stat_card(count: int, label: str, palette: Palette, accent: str | None = None) -> str:
    """One severity total. The rank's ink is the rule across its top as well
    as the numeral, so the four cards read as a ramp at a glance rather than
    as four identical boxes with differently coloured digits."""
    tint = accent or palette.border_strong
    return (
        f'<div class="stat-card" style="border-top-color:{tint}">'
        f'<div class="num" style="color: {tint}">{count}</div>'
        f'<div class="label">{_esc(label)}</div></div>'
    )


#: How many places a grouped finding names in full before the rest become a
#: count. Enough to see the pattern - is this the whole site or three pages -
#: without a card that is nothing but a list of URLs.
_LOCATIONS_SHOWN = 12


def _locations_block(finding, labels: dict) -> str:
    """Where the problem is: one line when it is in one place, a counted list
    when the same problem was found in several."""
    places = finding.locations or ([finding.location] if finding.location else [])
    if len(places) <= 1:
        return f'<p class="location">{_esc(places[0] if places else "")}</p>'
    shown = places[:_LOCATIONS_SHOWN]
    items = "".join(f'<li>{_esc(where)}</li>' for where in shown)
    rest = len(places) - len(shown)
    more = (f'<li class="more">{_esc(labels["and_more"]).format(count=rest)}</li>'
            if rest > 0 else "")
    return (
        f'<p class="location">{_esc(labels["found_in"]).format(count=len(places))}</p>'
        f'<ul class="locations">{items}{more}</ul>'
    )


def _meta_line(finding, labels: dict) -> str:
    """The technical identity of a finding, on one monospace line.

    `button-name · axe-core · <button> · 148` - which is the line the design
    bundle draws under a finding title (artboard 3a) and the line this
    document did not have. Every part of it was already known to the run and
    reached the JSON only: a reader with the printed report in hand could not
    say which check produced a row, so they could not look it up, suppress
    it, or compare it against the previous run.
    """
    bits = []
    if finding.rule_id:
        bits.append(f'<span class="rule">{_esc(finding.rule_id)}</span>')
    if finding.engine:
        bits.append(f'<span class="engine">{_esc(finding.engine)}</span>')
    if finding.element:
        bits.append(f'<span class="elem t-{role_of(finding.element)}">'
                    f'&lt;{_esc(finding.element)}&gt;</span>')
    if finding.agreement > 1:
        bits.append('<span class="agree">'
                    f'{_esc(labels["agreement"].format(count=finding.agreement))}</span>')
    if finding.occurrences > 1:
        bits.append(f'<span class="occ">{_esc(labels["occurrences"])} '
                    f'{finding.occurrences}</span>')
    if not bits:
        return ""
    return '<p class="finding-meta">' + '<span class="dot">·</span>'.join(bits) + '</p>'


def _finding_card(finding, lang: str, palette: Palette) -> str:
    labels = _labels(lang)
    rank = min(max(finding.severity_rank, 0), 3)
    severity_label = _SEVERITY_LABEL[rank].get(lang, _SEVERITY_LABEL[rank]["en"])
    category_label = labels["cat"].get(finding.category, finding.category)
    # `sev-N` inks the badge and the left rule. It is deliberately *not* on
    # the article any more: it used to be, and because the same class also
    # carries a background, every finding sat on a tinted panel and the whole
    # page read as a wash of red and amber. Severity is one fact about a
    # finding, not the surface it is printed on - so the panel is the
    # palette's neutral inset tone for all four ranks, and the rank shows in
    # the rule down its left edge and in one badge.
    parts = [
        f'<article class="finding rule-{rank}">',
        '<div class="finding-badges">',
        f'<span class="badge sev-{rank}">{_esc(severity_label)}</span>',
        f'<span class="badge badge-outline">{_esc(category_label)}</span>',
    ]
    # How settled it is, when it is not simply settled. `exact` gets no
    # badge: a document where most rows carry one would be teaching the
    # reader to ignore it, and "we measured this" is the default claim.
    if finding.confidence and finding.confidence != EXACT:
        label = labels["cert"].get(finding.confidence, finding.confidence)
        parts.append(f'<span class="badge badge-cert cert-{_esc(finding.confidence)}">'
                     f'{_esc(label)}</span>')
    if finding.owner:
        parts.append('<span class="badge badge-owner">'
                     f'{_esc(labels["owner"].format(platform=finding.owner))}</span>')
    parts.append('</div>')
    parts.append(f'<h3>{_esc(finding.title)}</h3>')
    parts.append(_meta_line(finding, labels))
    parts.append(_locations_block(finding, labels))

    if finding.category == CATEGORY_AI_TEXT:
        if finding.why:
            parts.append(_field(labels["why"], finding.why, escape=True))
        if finding.snippet:
            parts.append(_field_pre(labels["found"], finding.snippet, "found"))
        if finding.replacement:
            parts.append(_field_pre(labels["replacement"], finding.replacement, "fix"))
    else:
        if finding.found:
            parts.append(_field(labels["found"], finding.found, escape=True))
        if finding.why:
            parts.append(_field(labels["why"], finding.why, escape=True))
        if finding.fix:
            parts.append(_field(labels["fix"], finding.fix, escape=True,
                                kind="solution"))
        if finding.snippet:
            parts.append(_field_pre(labels["found_markup"], finding.snippet, "found"))
        if finding.replacement:
            parts.append(_field_pre(labels["fix_markup"], finding.replacement, "fix"))
        if finding.wcag:
            parts.append(
                f'<p class="wcag">{_esc(labels["wcag"])}: '
                f'{_esc(", ".join(finding.wcag))}</p>')

    # What this finding is *not*. Written by `audit.explanations` and shown
    # by the window and the terminal since they existed; the document a
    # person hands to somebody else printed the claim without its limit.
    if finding.caveat:
        parts.append(f'<p class="caveat">{_esc(finding.caveat)}</p>')
    parts.append('</article>')
    return "\n".join(parts)


def _field(label: str, value: str, escape: bool, kind: str = "") -> str:
    """A prose field. `kind="solution"` marks the one that says what to do -
    the only prose in a finding a reader acts on rather than reads, so it is
    the only prose that is inked."""
    body = _esc(value) if escape else value
    css = f"field field-{kind}" if kind else "field"
    return (f'<div class="{css}"><div class="label">{_esc(label)}</div>'
            f'<div class="value">{body}</div></div>')


#: The gutter mark on each half of the diff. Two characters, from the design
#: bundle's own finding panel (artboard 3a) and from every diff a developer
#: has ever read: what is there now, and what should be.
_DIFF_MARK = {"found": "\u2212", "fix": "+"}


def _field_pre(label: str, value: str, kind: str = "") -> str:
    """Quoted markup, syntax-inked, on the side of the diff it belongs to.

    Two blocks under one finding used to be typographically identical, so
    "this is what you have" and "this is what to write" could only be told
    apart by reading both. Now the ink says which is which before either is
    read, and inside them the element names are coloured by role - see
    `report.markup`, which owns both schemes and keeps them from colliding.
    """
    mark = _DIFF_MARK.get(kind, "")
    gutter = f'<span class="mark">{_esc(mark)}</span>' if mark else ""
    css = f"snippet snip-{kind}" if kind else "snippet"
    return (f'<div class="field"><div class="label">{_esc(label)}</div>'
            f'<pre class="{css}">{gutter}{highlight(value)}</pre></div>')


def _legend(findings, labels: dict, lang: str) -> str:
    """What the element colours mean, for the roles this report actually uses.

    Printed once, in the overview, rather than repeated per finding: a legend
    is read at most twice and then remembered.
    """
    roles = roles_used(findings)
    if len(roles) < 2:
        return ""
    names = ROLE_LABELS.get(lang, ROLE_LABELS["en"])
    items = "".join(
        f'<span class="legend-item"><span class="swatch t-{role}">&#9632;</span>'
        f'{_esc(names.get(role, role))}</span>'
        for role in roles)
    return (f'<div class="legend"><span class="legend-title">'
            f'{_esc(labels["legend"])}</span>{items}</div>')


#: Rows of the pages table before it is cut short. A crawl of a large site
#: listed every page it touched - 192 numbered lines on a real run - which is
#: an index, not a finding, and it pushed the actual problems several pages
#: further back.
_PAGES_SHOWN = 40

#: Characters shown per character-tally row.
_CHAR_ROWS = 12


def _what_was_found(model: ReportModel, by_category: dict, labels: dict) -> str:
    """Every kind of thing the run found, as one table.

    Grouped by where it comes from - the audit's categories, the AI-text
    pass's confidence bands, the character pass's tallies - because those are
    three different questions being answered on one page, and a reader needs
    to see which is which. What they must not have to do is find three tables
    in three places to compare them.
    """
    rows = []
    for cat, count in sorted(by_category.items(), key=lambda kv: -kv[1]):
        rows.append((_esc(labels["cat"].get(cat, cat)), "", count))

    ai = model.ai_patterns or {}
    if ai.get("total", 0):
        for band in ("high", "medium", "low"):
            count = ai.get(band, 0)
            if count:
                rows.append((_esc(labels["ai_patterns"]),
                             _esc(labels["confidence"]) + ": " + _esc(band),
                             count))

    typo = model.typography or {}
    if typo.get("total", 0):
        characters = sorted((typo.get("by_character") or {}).items(),
                            key=lambda kv: -kv[1])
        for name, count in characters[:_CHAR_ROWS]:
            rows.append((_esc(labels["typography"]), _esc(name), count))
        rest = sum(count for _n, count in characters[_CHAR_ROWS:])
        if rest:
            rows.append((_esc(labels["typography"]),
                         _esc(labels["and_more"].format(
                             count=len(characters) - _CHAR_ROWS)), rest))

    if not rows:
        return ""
    body = "".join(
        f'<tr><td>{group}</td><td class="detail">{detail}</td>'
        f'<td class="num">{count}</td></tr>'
        for group, detail, count in rows)
    return (f'<table class="category-table find-table">'
            f'<tr><th>{_esc(labels["source_group"])}</th>'
            f'<th>{_esc(labels["detail"])}</th>'
            f'<th class="num">{_esc(labels["count"])}</th></tr>{body}</table>')


def _bar_chart(pairs, labels_by_key, palette, colours=None) -> str:
    """A horizontal bar chart in plain CSS.

    No script and no image: `printToPdf` is the consumer, and a chart that
    depends on either is a chart that sometimes prints blank. Widths are
    percentages of the largest bar, so the shape is readable even when the
    counts run to five digits.
    """
    pairs = [(key, value) for key, value in pairs if value]
    if not pairs:
        return ""
    top = max(value for _k, value in pairs) or 1
    rows = []
    for key, value in pairs:
        width = max(2.0, value / top * 100)
        colour = (colours or {}).get(key, palette.accent)
        rows.append(
            f'<div class="bar-row">'
            f'<span class="bar-label">{_esc(labels_by_key.get(key, key))}</span>'
            f'<span class="bar-track">'
            f'<span class="bar-fill" style="width:{width:.1f}%;'
            f'background:{colour}"></span></span>'
            f'<span class="bar-num">{value}</span></div>')
    return "".join(rows)


def _charts(by_severity: dict, by_category: dict, labels: dict, palette,
            lang: str) -> str:
    """The two charts that open the report.

    Counts in a table are exact and shapeless; a reader looking at a summary
    wants to know where the weight is before reading a number. Both are here,
    which is why the table below them is not redundant.
    """
    severity_labels, severity_colours, severity_pairs = {}, {}, []
    for rank, names in ((0, ("critical", "high")), (1, ("serious", "medium")),
                        (2, ("moderate", "low")), (3, ("minor",))):
        count = sum(by_severity.get(name, 0) for name in names)
        key = f"rank{rank}"
        severity_labels[key] = _SEVERITY_LABEL[rank].get(
            lang, _SEVERITY_LABEL[rank]["en"])
        # The palette's own four-step ramp, not `error`/`amber`/`amber`.
        # Ranks 1 and 2 were both `palette.amber`, so "serious" and
        # "moderate" drew as the same colour and a four-step chart read as
        # three - the defect the ramp exists to prevent, in the one artifact
        # whose whole job is to show where the weight is. Same four tokens
        # the window's `SeverityBar` and the TUI's summary table paint with.
        severity_colours[key] = _severity_inks(palette)[rank]
        severity_pairs.append((key, count))

    severity_bars = _bar_chart(severity_pairs, severity_labels, palette,
                               severity_colours)
    category_bars = _bar_chart(
        sorted(by_category.items(), key=lambda kv: -kv[1]),
        labels["cat"], palette)
    if not severity_bars and not category_bars:
        return ""

    blocks = []
    for title, bars in ((labels["chart_severity"], severity_bars),
                        (labels["chart_category"], category_bars)):
        if bars:
            blocks.append(f'<div class="chart"><h3>{_esc(title)}</h3>{bars}</div>')
    return f'<div class="charts">{"".join(blocks)}</div>'


def _where_the_work_is(model: ReportModel, labels: dict, palette) -> str:
    """The two questions a reader has after the totals: *what* repeats, and
    *where*. Neither was answered anywhere in this document - severity and
    category say how bad and what kind, and a person schedules work by
    neither.
    """
    problems = model.counts_by_title()
    places = model.counts_by_place()
    if not problems and not places:
        return ""

    def rows(pairs) -> str:
        widest = max((count for *_rest, count in pairs), default=0) or 1
        out = []
        for row in pairs:
            label, count = (row[0], row[2]) if len(row) == 3 else row
            width = max(2, round(100 * count / widest))
            # The label is a whole line of its own above its bar, not a
            # 42%-wide column with an ellipsis on it. Rule names run long -
            # "This element has insufficient contrast at this conformance
            # level. Expected a contrast ratio of at least 4.5:1, but text..."
            # was what the column printed - and a ranked list of jobs whose
            # rows all end in "..." names none of them.
            out.append(
                f'<div class="rank-row">'
                f'<span class="rank-label">{_esc(label)}</span>'
                f'<span class="rank-bar">'
                f'<span class="rank-track">'
                f'<span class="rank-fill" style="width:{width}%"></span></span>'
                f'<span class="rank-num">{count}</span></span></div>')
        return "".join(out)

    blocks = []
    if problems:
        blocks.append(f'<div class="rank-block"><h3>{_esc(labels["top_problems"])}'
                      f'</h3>{rows(problems)}</div>')
    if places:
        blocks.append(f'<div class="rank-block"><h3>{_esc(labels["top_places"])}'
                      f'</h3>{rows(places)}</div>')
    return (f'<section class="work"><h2>{_esc(labels["where_work"])}</h2>'
            f'<div class="rank-grid">{"".join(blocks)}</div></section>')


def _rank_css(palette) -> str:
    """A ranked bar list. Same ink as the charts above it, tighter: this is
    read as a list of jobs, not as a picture of proportions."""
    return f"""
.work {{ margin-top: 8mm; }}
.rank-grid {{ display: flex; gap: 8mm; flex-wrap: wrap; }}
.rank-block {{ flex: 1 1 70mm; min-width: 62mm; }}
.rank-block h3 {{ font-size: 9pt; margin: 0 0 2.5mm; color: {palette.text_muted};
  text-transform: uppercase; letter-spacing: .05em; }}
.rank-row {{ margin-bottom: 2.4mm; break-inside: avoid; }}
/* The label gets a whole line. It used to be a 42% column with an ellipsis,
   which on real rule names printed a ranked list of jobs where every row
   ended in "..." and named none of them. */
.rank-label {{ display: block; font-size: 9pt; color: {palette.text};
  overflow-wrap: anywhere; margin-bottom: .6mm; }}
.rank-bar {{ display: flex; align-items: center; gap: 2mm; }}
.rank-track {{ flex: 1; height: 2mm; background: {palette.bg_muted}; }}
.rank-fill {{ display: block; height: 100%; background: {palette.accent}; }}
.rank-num {{ flex: 0 0 9mm; text-align: right; font-size: 9pt;
  color: {palette.text_muted}; font-variant-numeric: tabular-nums; }}
"""


def _pages_section(model: ReportModel, labels: dict) -> str:
    """What was examined, as a compact table rather than a numbered list.

    A crawl of 192 pages produced 192 numbered lines in 10.5pt type, several
    printed pages of index before the first finding. It is context, not
    content: it belongs in small type, sorted so the pages carrying the most
    problems come first, and cut off once it stops informing.
    """
    if not model.pages:
        return ""
    pages = sorted(model.pages,
                   key=lambda p: -(p.get("findings_count") or 0))
    rows = "".join(
        f'<tr><td>{_esc(p.get("source", ""))}</td>'
        f'<td class="num">{p.get("findings_count", 0)}</td></tr>'
        for p in pages[:_PAGES_SHOWN])
    extra = len(pages) - _PAGES_SHOWN
    if extra > 0:
        rows += (f'<tr class="more"><td colspan="2">'
                 f'{_esc(labels["pages_more"].format(count=extra))}</td></tr>')
    return (f'<section class="pages"><h2>{_esc(labels["pages_examined"])} '
            f'({len(pages)})</h2>'
            f'<table class="category-table pages-table">'
            f'<tr><th>{_esc(labels["page_col"])}</th>'
            f'<th class="num">{_esc(labels["count"])}</th></tr>'
            f'{rows}</table></section>')


def _top_patterns_section(model: ReportModel, labels: dict) -> str:
    """The highest-scoring passages, kept as detail rather than as a summary.

    The confidence tally that used to head this section now lives in the one
    "what was found" table; what is left here is the part that cannot go in a
    tally - the actual text, and why it scored.
    """
    ai = model.ai_patterns or {}
    top = ai.get("top_patterns") or []
    if not top:
        return ""
    rows = []
    for p in top:
        explanation = _esc(p.get("explanation", ""))
        # A repo path is not a fifth column - most reports have none to show,
        # and a column empty in every row but a few reads as a layout defect
        # rather than as "this one is different". It rides inside the
        # explanation cell instead, on its own line, only where it exists.
        if p.get("source_file"):
            note = labels["source_at"].format(
                path=p["source_file"], line=p.get("source_line", 0))
            explanation += f'<div class="src">{_esc(note)}</div>'
        rows.append(
            f'<tr><td class="num">{p.get("score", 0):.2f}</td>'
            f'<td>{_esc(p.get("confidence", ""))}</td>'
            f'<td class="passage">{_esc(p.get("text", ""))}</td>'
            f'<td>{explanation}</td></tr>')
    coverage = ""
    if ai.get("repo_total"):
        note = labels["repo_coverage"].format(
            matched=ai.get("repo_matched", 0), total=ai["repo_total"])
        coverage = f'<p class="repo-coverage">{_esc(note)}</p>'
    return (f'<section class="ai-patterns"><h2>{_esc(labels["top_patterns"])}'
            f'</h2>{coverage}<table class="category-table">'
            f'<tr><th class="num">{_esc(labels["score"])}</th>'
            f'<th>{_esc(labels["confidence"])}</th>'
            f'<th>{_esc(labels["text"])}</th>'
            f'<th>{_esc(labels["explanation"])}</th></tr>{"".join(rows)}</table></section>')


def render_html(model: ReportModel, lang: str = "en") -> str:
    """`ReportModel` -> a complete `<html>` document, ready for a browser or
    for `report.pdf.render_pdf`.

    Always the light `Palette`: the report is paper (or a PDF standing in
    for paper), and dark-mode colours that read well on a screen are the
    wrong contrast on white — see the module docstring.
    """
    if lang not in _LABELS:
        lang = "en"
    labels = _labels(lang)
    # *With* the desktop overlay: the XAnalyze design bundle read as tokens.
    # This document used to take the plain xFormat web palette instead, on
    # the argument that a report is paper and the overlay's muted hues are a
    # screen decision. That argument was wrong twice over. The overlay is not
    # a screen tint - it is this product's palette, the one the bundle's own
    # report artboard (3h) is drawn in, down to the severity dots; and the
    # web palette's #e5484d beside the window's #c0564f meant one run showed
    # a person two different reds for one severity depending on which
    # surface they were looking at.
    palette = palettes(overlay=True)["light"]

    # Grouped, not raw: one card per distinct problem, carrying every place
    # it was found. A thirty-page crawl of a site with a shared header used
    # to print the header's every fault thirty times. See
    # `ReportModel.grouped_findings`.
    findings = model.grouped_findings()
    by_severity: dict = {}
    by_category: dict = {}
    for finding in findings:
        by_severity[finding.severity] = by_severity.get(finding.severity, 0) + 1
        by_category[finding.category] = by_category.get(finding.category, 0) + 1
    mode_label = labels["mode"].get(model.meta.mode, model.meta.mode)
    logo = _logo_data_uri()

    stat_cards = []
    for rank in range(4):
        names = [name for name, r in
                 (("critical", 0), ("high", 0), ("serious", 1), ("medium", 1),
                  ("moderate", 2), ("low", 2), ("minor", 3))
                 if r == rank]
        count = sum(by_severity.get(name, 0) for name in names)
        if count == 0 and rank not in (0,):
            continue
        label = _SEVERITY_LABEL[rank].get(lang, _SEVERITY_LABEL[rank]["en"])
        # The same four-step ramp as the chart three lines below it. These
        # were two different maps, so "serious" was orange in the bar and
        # amber in the card that counts it.
        accent = _severity_inks(palette)[rank]
        stat_cards.append(_stat_card(count, label, palette, accent))

    # One table, not four. The category counts, the AI-pattern confidence
    # bands and the character tallies were three tables in three sections
    # separated by the findings, so a reader asking "what kind of thing did
    # this find" had to hold three places at once and never saw them beside
    # each other. They answer the same question and now sit in one answer.
    what_rows = _what_was_found(model, by_category, labels)

    charts = _charts(by_severity, by_category, labels, palette, lang)
    legend = _legend(findings, labels, lang)

    findings_html = ("".join(_finding_card(f, lang, palette) for f in findings)
                     if findings else f'<p class="empty">{_esc(labels["no_findings"])}</p>')

    work_section = _where_the_work_is(model, labels, palette)
    pages_section = _pages_section(model, labels)
    ai_section = _top_patterns_section(model, labels)
    typo_section = ""

    doc_title = f'{labels["title"]} — {model.meta.target}' if model.meta.target else labels["title"]

    style = f"""
@page {{ size: A4; margin: 0; }}
* {{ box-sizing: border-box; }}
html, body {{ margin: 0; padding: 0; }}
/* Inline-only: text gets a horizontal gutter, the tint behind it does not -
   see the module docstring. On screen there is no `@page` at all and the
   window itself has no tint to bleed, so the screen rule adds a matching
   top/bottom padding too - a document opened in a browser tab, not a paper
   simulation. */
@media screen {{
  body {{ padding: 16mm {CONTENT_PADDING_H_MM}mm 20mm; max-width: 260mm; margin: 0 auto; }}
}}
@media print {{ body {{ padding: 0 {CONTENT_PADDING_H_MM}mm; max-width: none; }} }}
/* Not one rounded corner anywhere in this document. A radius says "card",
   "app", "surface"; this is a technical report, and its blocks are meant to
   read as regions of a printed page rather than as widgets lifted off one.
   Everything that used to be a pill or a rounded panel is a rectangle with a
   hairline or a rule down one edge. */
body {{
  font-family: '{palette.font}', Arial, sans-serif;
  font-size: 10.5pt; line-height: 1.5;
  color: {palette.text}; background: {palette.bg};
}}
a {{ color: {palette.accent}; }}
h1, h2, h3 {{ font-family: '{palette.font}', Arial, sans-serif; color: {palette.text}; }}
.report-header {{
  display: flex; align-items: center; gap: 6mm;
  border-bottom: 1px solid {palette.border}; padding-bottom: 5mm; margin-bottom: 8mm;
}}
.report-header img {{ width: 22mm; height: auto; flex: 0 0 auto; }}
.report-header h1 {{ font-size: 17pt; margin: 0 0 1.5mm; overflow-wrap: anywhere; }}
.report-header .meta {{ margin: 0; font-size: 9pt; color: {palette.text_muted}; }}
.report-header .run {{ margin: 1.5mm 0 0; font-size: 8pt; color: {palette.text_muted};
  overflow-wrap: anywhere; }}
/* Not `break-inside: avoid`. The overview carries charts and a table and is
   taller than it was; forbidding a break inside it meant that whenever it did
   not fit in what was left of page one, the whole block jumped to page two and
   left most of page one blank. It may break; its headings may not be stranded,
   which is what the rules below say. */
.summary {{ margin-bottom: 9mm; }}
.summary h2 {{ font-size: 12pt; margin: 0 0 3mm; }}
h2, h3 {{ break-after: avoid; page-break-after: avoid; }}
.table-title {{ font-size: 10pt; margin: 6mm 0 2mm; color: {palette.text_muted};
  text-transform: uppercase; letter-spacing: .05em; }}

/* Charts: plain CSS bars, no script and no image, because `printToPdf` is
   the consumer and anything else sometimes prints blank. */
.charts {{ display: flex; gap: 8mm; margin: 4mm 0 2mm; }}
.chart {{ flex: 1 1 0; min-width: 0; break-inside: avoid; }}
.chart h3 {{ font-size: 8.5pt; margin: 0 0 2mm; color: {palette.text_muted};
  text-transform: uppercase; letter-spacing: .05em; font-weight: 600; }}
.bar-row {{ display: flex; align-items: center; gap: 2mm; margin: 1.2mm 0;
  font-size: 8.3pt; break-inside: avoid; }}
.bar-label {{ flex: 0 0 26mm; color: {palette.text_muted};
  overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }}
.bar-track {{ flex: 1 1 auto; height: 3mm; background: {palette.bg_muted}; }}
.bar-fill {{ display: block; height: 100%; }}
.bar-num {{ flex: 0 0 auto; font-variant-numeric: tabular-nums;
  font-weight: 600; min-width: 9mm; text-align: right; }}
.stat-grid {{ display: flex; flex-wrap: wrap; gap: 4mm; margin-bottom: 5mm; }}
.stat-card {{
  flex: 1 1 26mm; border: 1px solid {palette.border};
  border-top: 1mm solid {palette.border_strong};
  padding: 3mm 4mm; text-align: center; background: {palette.bg};
}}
.stat-card .num {{ font-size: 17pt; font-weight: 700; }}
.stat-card .label {{
  font-size: 7.5pt; color: {palette.text_muted}; text-transform: uppercase; letter-spacing: .04em;
}}

/* The element-colour legend. Printed once, and only for the roles this
   report actually contains - see `_legend`. */
.legend {{
  display: flex; flex-wrap: wrap; align-items: baseline; gap: 1.5mm 4mm;
  margin: 3mm 0 0; padding: 2mm 3mm; background: {palette.bg_muted};
  border-left: 1mm solid {palette.border_strong};
  font-size: 8pt; color: {palette.text_muted}; break-inside: avoid;
}}
.legend-title {{ text-transform: uppercase; letter-spacing: .05em; font-weight: 600; }}
.legend-item {{ white-space: nowrap; }}
.legend .swatch {{ margin-right: 1mm; font-size: 7pt; }}

table.category-table {{ width: 100%; border-collapse: collapse; font-size: 9pt; }}
table.category-table th, table.category-table td {{
  text-align: left; padding: 1.6mm 2mm; border-bottom: 1px solid {palette.border};
  vertical-align: top;
}}
table.category-table th {{ color: {palette.text_muted}; font-weight: 600;
  text-transform: uppercase; letter-spacing: .04em; font-size: 8pt; }}
/* A row may not be split across pages; the table may. The header repeats on
   each page it continues onto, so a table that spans a break stays readable. */
table.category-table tr {{ break-inside: avoid; page-break-inside: avoid; }}
table.category-table thead {{ display: table-header-group; }}
table.category-table td.num, table.category-table th.num {{
  text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap;
}}
table.find-table td.detail {{ color: {palette.text_muted}; }}
/* The quoted passage in the AI-text table: it used to be cut at 80
   characters, which on a page this wide was clipping prose that had room to
   wrap. A cell wraps. */
table.category-table td.passage {{ overflow-wrap: anywhere; }}
/* The repo path rides inside the explanation cell rather than its own
   column - see `_top_patterns_section` - so it needs to read as an aside,
   not as more of the explanation. */
table.category-table .src {{
  color: {palette.text_muted}; font-size: 8pt; margin-top: 1mm;
  font-family: ui-monospace, "SF Mono", Menlo, Consolas, monospace;
}}
.repo-coverage {{ color: {palette.text_muted}; font-size: 9pt; margin: -1mm 0 2mm; }}
/* The index of what was examined is context, not content: small type, and a
   fixed narrow column for the count so the addresses get the width. */
table.pages-table {{ font-size: 8pt; }}
table.pages-table td {{ padding: 1mm 2mm; overflow-wrap: anywhere; }}
table.pages-table tr.more td {{ color: {palette.text_muted}; font-style: italic; }}
.findings h2 {{ font-size: 12pt; margin: 0 0 4mm; }}

/* Cards may break across pages. Forbidding it is what left large blank areas:
   a tall card that did not fit in the remainder of a page moved to the next
   one whole, and the space it vacated stayed empty. What actually has to hold
   is that a card's heading is never the last thing on a page and a stray line
   never opens one - which is what `break-after` above and orphans/widows here
   say, without wasting a third of every page to say it. */
.finding {{
  break-inside: auto; orphans: 3; widows: 3;
  border: 1px solid {palette.border};
  padding: 5mm 6mm; margin-bottom: 5mm;
  background: {palette.bg_muted};
}}
/* Severity is a rule down the edge, not a wash over the panel. */
{_rule_css(palette)}
.finding h3 {{ font-size: 10.8pt; margin: 0 0 1.2mm; overflow-wrap: anywhere;
  break-after: avoid; page-break-after: avoid; }}
.finding-meta {{
  font-family: '{palette.font_mono}', ui-monospace, Menlo, monospace;
  font-size: 8pt; color: {palette.text_muted}; margin: 0 0 1.5mm;
  overflow-wrap: anywhere;
}}
.finding-meta .dot {{ margin: 0 1.6mm; color: {palette.text_subtle}; }}
.finding-meta .rule {{ color: {palette.text}; font-weight: 600; }}
.finding .location {{
  font-size: 8.3pt; color: {palette.text_muted}; margin: 0 0 3mm; overflow-wrap: anywhere;
}}
.finding ul.locations {{
  margin: -1.5mm 0 3mm; padding-left: 5mm; font-size: 8.3pt;
  color: {palette.text_muted}; list-style: square;
}}
.finding ul.locations li {{ overflow-wrap: anywhere; margin: 0.3mm 0; }}
.finding ul.locations li.more {{ list-style: none; margin-left: -3mm; font-style: italic; }}
.finding-badges {{ margin-bottom: 2mm; }}
.badge {{
  display: inline-block; padding: .5mm 2mm; font-size: 7.3pt;
  font-weight: 600; text-transform: uppercase; letter-spacing: .03em; margin-right: 1.5mm;
}}
.badge-outline {{ border: 1px solid {palette.border_strong}; color: {palette.text_muted}; }}
{_severity_css(palette)}
{_rank_css(palette)}
{role_css(palette)}
/* Small blocks stay whole: these are short, so keeping them together costs
   a line or two of slack rather than a third of a page. */
.field {{ margin: 2mm 0; break-inside: avoid; }}
.field .label {{
  font-weight: 600; font-size: 8.2pt; color: {palette.text_muted};
  text-transform: uppercase; letter-spacing: .03em; margin-bottom: .8mm;
}}
.field .value {{ font-size: 9.6pt; overflow-wrap: anywhere; }}
/* The one prose field a reader acts on rather than reads. Inked in the same
   green as the `+` half of the diff below it, because it is the same claim
   in words: this is what to do. */
.field-solution {{ border-left: .7mm solid {palette.success_text}; padding-left: 2.5mm; }}
.field-solution .label {{ color: {palette.success_text}; }}
pre.snippet {{
  font-family: '{palette.font_mono}', ui-monospace, 'Courier New', monospace;
  font-size: 8.4pt; line-height: 1.45;
  white-space: pre-wrap; overflow-wrap: anywhere; word-break: break-word;
  background: {palette.bg}; border: 1px solid {palette.border};
  border-left: .7mm solid {palette.border_strong};
  padding: 2mm 3mm; margin: 0;
}}
/* Which half of the diff. Red is what is there, green is what should be -
   the only two things in this document those colours mean. */
pre.snip-found {{ border-left-color: {palette.error_text}; }}
pre.snip-fix {{ border-left-color: {palette.success_text}; }}
pre.snippet .mark {{
  display: inline-block; width: 3mm; margin-left: -1mm; font-weight: 700;
}}
pre.snip-found .mark {{ color: {palette.error_text}; }}
pre.snip-fix .mark {{ color: {palette.success_text}; }}
.wcag {{ font-size: 8pt; color: {palette.text_muted}; margin: 1.5mm 0 0; }}
/* The limit of a finding, in the finding. Set apart by a rule rather than by
   italics: it is a statement about the row above it, not an aside. */
.caveat {{
  font-size: 8.4pt; color: {palette.text_muted}; margin: 2.5mm 0 0;
  padding-left: 2.5mm; border-left: .7mm solid {palette.border_strong};
}}
.badge-cert {{ border: 1px solid {palette.border_strong}; color: {palette.text_muted}; }}
.badge.cert-{ADVISORY} {{ color: {palette.amber_text}; border-color: {palette.amber}; }}
.badge.cert-{NEEDS_BROWSER} {{ color: {palette.text_muted}; border-style: dashed; }}
.badge-owner {{ border: 1px dashed {palette.border_strong}; color: {palette.text_muted}; }}
.empty {{ color: {palette.text_muted}; }}
footer {{
  margin-top: 8mm; padding-top: 3mm; border-top: 1px solid {palette.border};
  font-size: 7.8pt; color: {palette.text_muted}; text-align: center;
}}
""".strip()

    logo_img = f'<img src="{logo}" alt="">' if logo else ""

    run_line = ""
    if getattr(model.meta, "run", None):
        # One line rather than a table: it is the document's passport, not
        # its content, and a reader checks it once. Every parameter that
        # changed what was measured is in it - see `cli_impl.runheader`.
        run_line = ('<p class="run">'
                    + _esc(" · ".join(f"{label} {value}"
                                      for label, value in model.meta.run))
                    + "</p>")
    return f"""<!doctype html>
<html lang="{_esc(lang)}">
<head>
<meta charset="utf-8">
<title>{_esc(doc_title)}</title>
<style>{style}</style>
</head>
<body>
<header class="report-header">
  {logo_img}
  <div>
    <h1>{_esc(model.meta.target or labels["title"])}</h1>
    <p class="meta">{_esc(mode_label)} &middot; {_esc(labels["generated"])} {_esc(model.meta.generated_at)}</p>
    {run_line}
  </div>
</header>

<section class="summary">
  <h2>{_esc(labels["overview"])}</h2>
  <div class="stat-grid">{"".join(stat_cards)}</div>
  {charts}
  <h3 class="table-title">{_esc(labels["what_found"])}</h3>
  {what_rows}
  {legend}
</section>

{work_section}

{ai_section}
{typo_section}

<section class="findings">
  <h2>{_esc(labels["findings"])} ({len(findings)})</h2>
  {findings_html}
</section>

{pages_section}

<footer>{_esc(labels["footer"])}</footer>
</body>
</html>
"""
