"""`ReportModel` -> a self-contained, print-ready HTML document.

Follows the same three print-CSS principles xFormat's own HTML export uses
(`apps/web/src/features/cv/cvHtmlTemplate.ts` in the `xformat` checkout,
read for the pattern only — it is a TypeScript/React template, nothing from
it is imported here):

* `@page { size: A4; margin: ... }` — real page geometry, not a CSS
  approximation of one. Unlike that template (which renders one continuous
  virtual page and lets a canvas-slicing pipeline carve it into PDF pages
  after the fact), this HTML is handed to `QWebEnginePage.printToPdf`
  directly — Chromium's own print pipeline paginates the flowing content,
  the same way "Print -> Save as PDF" does in a browser. So the page margin
  is declared once, in `@page`, and nothing here re-adds it as padding.
* Page breaks governed by what must stay together, not by what looks tidy.
  `break-inside: avoid` on every finding card was the obvious rule and the
  wrong one: a tall card that did not fit in the remainder of a page moved to
  the next page whole, and the space it left behind stayed blank — on a report
  of any size, a third of many pages. What actually has to hold is narrower —
  a heading is never the last thing on a page (`break-after: avoid`), a stray
  line never opens or closes one (`orphans`/`widows`), and small blocks (a
  field, a table row, a chart bar) stay whole. Cards and tables may break.
* mm/pt units throughout — a print document, not a screen one.

Colours and type come from `ui.tokens.Palette`, always the **light** theme:
the report is meant to be printed or read as a document, and a dark card on
white paper is illegible on a real printer — see `render_html`'s `lang`
default and the light-only choice below.
"""
from __future__ import annotations

import base64
import html
from pathlib import Path

from report.model import CATEGORY_AI_TEXT, ReportModel
from ui.tokens import Palette, palettes

#: Vendored alongside the app icon — see `ui/main_window.py`'s `ASSETS`.
#: Reading it from here rather than reaching into a sibling `xformat`
#: checkout (which may not exist on the machine building the report) keeps
#: the report generator, like the desktop app itself, buildable from this
#: repository alone.
_LOGO_PATH = Path(__file__).resolve().parent.parent / "ui" / "design" / "assets" / "logo-light.svg"

#: Minimal, self-contained labels for the report's own chrome. Not routed
#: through `i18n.translations.t()`: this package does not touch that module
#: (see the repository's task boundary), and a report has a small, fixed
#: vocabulary of its own rather than the UI's much larger one.
_LABELS = {
    "en": dict(
        title="Scan report", generated="Generated", target="Target",
        summary="Summary", by_severity="By severity", by_category="By category",
        findings="Findings", no_findings="No findings — nothing to report.",
        category="Category", count="Count", found="Found", why="Why it matters",
        fix="How to fix", replacement="Ready replacement", engine="Detected by",
        wcag="WCAG", footer="Generated by AI Content Scanner.",
        pages_examined="Pages examined", ai_patterns="AI-generated text patterns",
        typography="Typography issues (non-keyboard characters)",
        confidence="Confidence", text="Text", explanation="Explanation",
        character="Character", score="Score",
        overview="Overview", what_found="What was found", kind="Kind",
        source_group="Where it comes from", detail="Detail",
        chart_severity="By severity", chart_category="By category",
        pages_more="and {count} more pages", page_col="Page or file",
        top_patterns="Highest-scoring passages",
        found_in="Found in {count} places", and_more="and {count} more",
        occurrences="Occurrences",
        source_at="Source: {path}:{line}",
        repo_coverage="Matched to the given repository: {matched}/{total} passages",
        mode={"text-web": "AI-text scan · website", "text-repo": "AI-text scan · repository",
             "audit-web": "Site audit · website", "audit-repo": "Site audit · repository",
             "audit-file": "Site audit · page"},
        cat={"ai-text": "AI-sounding text", "accessibility": "Accessibility",
            "performance": "Performance", "seo": "SEO", "best-practices": "Best practices"},
    ),
    "uk": dict(
        title="Звіт сканування", generated="Створено", target="Ціль",
        summary="Зведення", by_severity="За тяжкістю", by_category="За категорією",
        findings="Знахідки", no_findings="Знахідок немає — звітувати нема про що.",
        category="Категорія", count="Кількість", found="Що знайдено", why="Чому це важливо",
        fix="Як виправити", replacement="Готова заміна", engine="Знайшов",
        wcag="WCAG", footer="Згенеровано AI Content Scanner.",
        pages_examined="Переглянуті сторінки", ai_patterns="AI-згенеровані текстові патерни",
        typography="Проблеми типографіки (символи без клавіатури)",
        confidence="Впевненість", text="Текст", explanation="Пояснення",
        character="Символ", score="Оцінка",
        overview="Огляд", what_found="Що знайдено", kind="Вид",
        source_group="Звідки", detail="Деталь",
        chart_severity="За тяжкістю", chart_category="За категорією",
        pages_more="і ще {count} сторінок", page_col="Сторінка або файл",
        top_patterns="Уривки з найвищою оцінкою",
        found_in="Знайдено у {count} місцях", and_more="і ще {count}",
        occurrences="Повторів",
        source_at="Джерело: {path}:{line}",
        repo_coverage="Знайдено в репозиторії: {matched}/{total} уривків",
        mode={"text-web": "Аналіз тексту · сайт", "text-repo": "Аналіз тексту · репозиторій",
             "audit-web": "Аудит доступності · сайт", "audit-repo": "Аудит доступності · репозиторій",
             "audit-file": "Аудит доступності · сторінка"},
        cat={"ai-text": "Схоже на текст ШІ", "accessibility": "Доступність",
            "performance": "Продуктивність", "seo": "SEO", "best-practices": "Найкращі практики"},
    ),
    "it": dict(
        title="Report di scansione", generated="Generato", target="Destinazione",
        summary="Riepilogo", by_severity="Per gravità", by_category="Per categoria",
        findings="Rilievi", no_findings="Nessun rilievo: niente da segnalare.",
        category="Categoria", count="Conteggio", found="Cosa è stato trovato",
        why="Perché è importante", fix="Come correggere", replacement="Sostituzione pronta",
        engine="Rilevato da", wcag="WCAG", footer="Generato da AI Content Scanner.",
        pages_examined="Pagine esaminate", ai_patterns="Pattern di testo generati da AI",
        typography="Problemi di tipografia (caratteri non da tastiera)",
        confidence="Confidenza", text="Testo", explanation="Spiegazione",
        character="Carattere", score="Punteggio",
        overview="Panoramica", what_found="Che cosa è stato trovato", kind="Tipo",
        source_group="Da dove viene", detail="Dettaglio",
        chart_severity="Per gravità", chart_category="Per categoria",
        pages_more="e altre {count} pagine", page_col="Pagina o file",
        top_patterns="Passaggi con punteggio più alto",
        found_in="Trovato in {count} punti", and_more="e altri {count}",
        occurrences="Occorrenze",
        source_at="Origine: {path}:{line}",
        repo_coverage="Corrispondenza nel repository indicato: {matched}/{total} passaggi",
        mode={"text-web": "Analisi testo · sito", "text-repo": "Analisi testo · repository",
             "audit-web": "Audit di accessibilità · sito",
             "audit-repo": "Audit di accessibilità · repository",
             "audit-file": "Audit di accessibilità · pagina"},
        cat={"ai-text": "Testo dall'aspetto artificiale", "accessibility": "Accessibilità",
            "performance": "Prestazioni", "seo": "SEO", "best-practices": "Best practice"},
    ),
}

#: One CSS class per rank so a mixed report (there is no such run today, but
#: nothing stops one) still paints consistently: rank 0-3, clamped, covers
#: both severity vocabularies (see `report.model.SEVERITY_RANK`).
_SEVERITY_LABEL = {
    0: {"en": "Critical", "uk": "Критично", "it": "Critico"},
    1: {"en": "Serious", "uk": "Серйозно", "it": "Grave"},
    2: {"en": "Moderate", "uk": "Помірно", "it": "Moderato"},
    3: {"en": "Minor", "uk": "Незначно", "it": "Minore"},
}


def _labels(lang: str) -> dict:
    return _LABELS.get(lang, _LABELS["en"])


def _logo_data_uri() -> str:
    try:
        raw = _LOGO_PATH.read_bytes()
    except OSError:
        return ""
    encoded = base64.b64encode(raw).decode("ascii")
    return f"data:image/svg+xml;base64,{encoded}"


def _rgba(hex_color: str, alpha: float) -> str:
    """`#rrggbb` -> `rgba(r, g, b, alpha)`, for a tinted badge background."""
    text = hex_color.lstrip("#")
    if len(text) == 3:
        text = "".join(ch * 2 for ch in text)
    if len(text) != 6:
        return hex_color
    try:
        r, g, b = (int(text[i:i + 2], 16) for i in (0, 2, 4))
    except ValueError:
        return hex_color
    return f"rgba({r}, {g}, {b}, {alpha})"


def _esc(value) -> str:
    """Escape anything interpolated into the document. Applied even to
    fields that are normally plain prose (a rule's `why`/`fix` text can
    still carry a raw `<` or `&` when it quotes an attribute value or a
    URL), and always to `snippet`/`replacement`, which are markup or code
    shown *as text* — never rendered as markup, per the task's escaping
    requirement."""
    return html.escape(str(value or ""), quote=True)


def _severity_css(palette: Palette) -> str:
    tiers = {
        0: (palette.error, _rgba(palette.error, 0.10)),
        1: (palette.amber, _rgba(palette.amber, 0.14)),
        2: (palette.amber, _rgba(palette.amber, 0.08)),
        3: (palette.text_muted, palette.bg_muted),
    }
    rules = []
    for rank, (fg, bg) in tiers.items():
        rules.append(
            f".sev-{rank} {{ color: {fg}; background: {bg}; }}\n"
            f".finding.sev-{rank} {{ border-left: 1.2mm solid {fg}; }}"
        )
    return "\n".join(rules)


def _stat_card(count: int, label: str, palette: Palette, accent: str | None = None) -> str:
    color = f"color: {accent};" if accent else ""
    return (
        f'<div class="stat-card"><div class="num" style="{color}">{count}</div>'
        f'<div class="label">{_esc(label)}</div></div>'
    )


#: How many places a grouped finding names in full before the rest become a
#: count. Enough to see the pattern - is this the whole site or three pages -
#: without a card that is nothing but a list of URLs.
_LOCATIONS_SHOWN = 12


def _locations_block(finding, labels: dict) -> str:
    """Where the problem is: one line when it is in one place, a counted list
    when the same problem was found in several."""
    places = finding.locations or ([finding.location] if finding.location else [])
    if len(places) <= 1:
        return f'<p class="location">{_esc(places[0] if places else "")}</p>'
    shown = places[:_LOCATIONS_SHOWN]
    items = "".join(f'<li>{_esc(where)}</li>' for where in shown)
    rest = len(places) - len(shown)
    more = (f'<li class="more">{_esc(labels["and_more"]).format(count=rest)}</li>'
            if rest > 0 else "")
    return (
        f'<p class="location">{_esc(labels["found_in"]).format(count=len(places))}</p>'
        f'<ul class="locations">{items}{more}</ul>'
    )


def _finding_card(finding, lang: str, palette: Palette) -> str:
    labels = _labels(lang)
    rank = min(max(finding.severity_rank, 0), 3)
    severity_label = _SEVERITY_LABEL[rank].get(lang, _SEVERITY_LABEL[rank]["en"])
    category_label = labels["cat"].get(finding.category, finding.category)
    parts = [
        f'<article class="finding sev-{rank}">',
        '<div class="finding-badges">',
        f'<span class="badge sev-{rank}">{_esc(severity_label)}</span>',
        f'<span class="badge badge-outline">{_esc(category_label)}</span>',
    ]
    if finding.engine:
        parts.append(f'<span class="badge badge-outline">{_esc(finding.engine)}</span>')
    parts.append('</div>')
    parts.append(f'<h3>{_esc(finding.title)}</h3>')
    parts.append(_locations_block(finding, labels))

    if finding.category == CATEGORY_AI_TEXT:
        if finding.why:
            parts.append(_field(labels["why"], finding.why, escape=True))
        if finding.snippet:
            parts.append(_field_pre(labels["found"], finding.snippet))
        if finding.replacement:
            parts.append(_field_pre(labels["replacement"], finding.replacement))
    else:
        if finding.found:
            parts.append(_field(labels["found"], finding.found, escape=True))
        if finding.why:
            parts.append(_field(labels["why"], finding.why, escape=True))
        if finding.fix:
            parts.append(_field(labels["fix"], finding.fix, escape=True))
        if finding.snippet:
            parts.append(_field_pre(labels["found"] + " —", finding.snippet))
        if finding.replacement:
            parts.append(_field_pre(labels["replacement"], finding.replacement))
        if finding.wcag:
            parts.append(
                f'<p class="wcag">{_esc(labels["wcag"])}: '
                f'{_esc(", ".join(finding.wcag))}</p>')

    parts.append('</article>')
    return "\n".join(parts)


def _field(label: str, value: str, escape: bool) -> str:
    body = _esc(value) if escape else value
    return (f'<div class="field"><div class="label">{_esc(label)}</div>'
            f'<div class="value">{body}</div></div>')


def _field_pre(label: str, value: str) -> str:
    return (f'<div class="field"><div class="label">{_esc(label)}</div>'
            f'<pre class="snippet">{_esc(value)}</pre></div>')


#: Rows of the pages table before it is cut short. A crawl of a large site
#: listed every page it touched - 192 numbered lines on a real run - which is
#: an index, not a finding, and it pushed the actual problems several pages
#: further back.
_PAGES_SHOWN = 40

#: Characters shown per character-tally row.
_CHAR_ROWS = 12


def _what_was_found(model: ReportModel, by_category: dict, labels: dict) -> str:
    """Every kind of thing the run found, as one table.

    Grouped by where it comes from - the audit's categories, the AI-text
    pass's confidence bands, the character pass's tallies - because those are
    three different questions being answered on one page, and a reader needs
    to see which is which. What they must not have to do is find three tables
    in three places to compare them.
    """
    rows = []
    for cat, count in sorted(by_category.items(), key=lambda kv: -kv[1]):
        rows.append((_esc(labels["cat"].get(cat, cat)), "", count))

    ai = model.ai_patterns or {}
    if ai.get("total", 0):
        for band in ("high", "medium", "low"):
            count = ai.get(band, 0)
            if count:
                rows.append((_esc(labels["ai_patterns"]),
                             _esc(labels["confidence"]) + ": " + _esc(band),
                             count))

    typo = model.typography or {}
    if typo.get("total", 0):
        characters = sorted((typo.get("by_character") or {}).items(),
                            key=lambda kv: -kv[1])
        for name, count in characters[:_CHAR_ROWS]:
            rows.append((_esc(labels["typography"]), _esc(name), count))
        rest = sum(count for _n, count in characters[_CHAR_ROWS:])
        if rest:
            rows.append((_esc(labels["typography"]),
                         _esc(labels["and_more"].format(
                             count=len(characters) - _CHAR_ROWS)), rest))

    if not rows:
        return ""
    body = "".join(
        f'<tr><td>{group}</td><td class="detail">{detail}</td>'
        f'<td class="num">{count}</td></tr>'
        for group, detail, count in rows)
    return (f'<table class="category-table find-table">'
            f'<tr><th>{_esc(labels["source_group"])}</th>'
            f'<th>{_esc(labels["detail"])}</th>'
            f'<th class="num">{_esc(labels["count"])}</th></tr>{body}</table>')


def _bar_chart(pairs, labels_by_key, palette, colours=None) -> str:
    """A horizontal bar chart in plain CSS.

    No script and no image: `printToPdf` is the consumer, and a chart that
    depends on either is a chart that sometimes prints blank. Widths are
    percentages of the largest bar, so the shape is readable even when the
    counts run to five digits.
    """
    pairs = [(key, value) for key, value in pairs if value]
    if not pairs:
        return ""
    top = max(value for _k, value in pairs) or 1
    rows = []
    for key, value in pairs:
        width = max(2.0, value / top * 100)
        colour = (colours or {}).get(key, palette.accent)
        rows.append(
            f'<div class="bar-row">'
            f'<span class="bar-label">{_esc(labels_by_key.get(key, key))}</span>'
            f'<span class="bar-track">'
            f'<span class="bar-fill" style="width:{width:.1f}%;'
            f'background:{colour}"></span></span>'
            f'<span class="bar-num">{value}</span></div>')
    return "".join(rows)


def _charts(by_severity: dict, by_category: dict, labels: dict, palette,
            lang: str) -> str:
    """The two charts that open the report.

    Counts in a table are exact and shapeless; a reader looking at a summary
    wants to know where the weight is before reading a number. Both are here,
    which is why the table below them is not redundant.
    """
    severity_labels, severity_colours, severity_pairs = {}, {}, []
    for rank, names in ((0, ("critical", "high")), (1, ("serious", "medium")),
                        (2, ("moderate", "low")), (3, ("minor",))):
        count = sum(by_severity.get(name, 0) for name in names)
        key = f"rank{rank}"
        severity_labels[key] = _SEVERITY_LABEL[rank].get(
            lang, _SEVERITY_LABEL[rank]["en"])
        severity_colours[key] = {0: palette.error, 1: palette.amber,
                                 2: palette.amber,
                                 3: palette.text_muted}[rank]
        severity_pairs.append((key, count))

    severity_bars = _bar_chart(severity_pairs, severity_labels, palette,
                               severity_colours)
    category_bars = _bar_chart(
        sorted(by_category.items(), key=lambda kv: -kv[1]),
        labels["cat"], palette)
    if not severity_bars and not category_bars:
        return ""

    blocks = []
    for title, bars in ((labels["chart_severity"], severity_bars),
                        (labels["chart_category"], category_bars)):
        if bars:
            blocks.append(f'<div class="chart"><h3>{_esc(title)}</h3>{bars}</div>')
    return f'<div class="charts">{"".join(blocks)}</div>'


def _pages_section(model: ReportModel, labels: dict) -> str:
    """What was examined, as a compact table rather than a numbered list.

    A crawl of 192 pages produced 192 numbered lines in 10.5pt type, several
    printed pages of index before the first finding. It is context, not
    content: it belongs in small type, sorted so the pages carrying the most
    problems come first, and cut off once it stops informing.
    """
    if not model.pages:
        return ""
    pages = sorted(model.pages,
                   key=lambda p: -(p.get("findings_count") or 0))
    rows = "".join(
        f'<tr><td>{_esc(p.get("source", ""))}</td>'
        f'<td class="num">{p.get("findings_count", 0)}</td></tr>'
        for p in pages[:_PAGES_SHOWN])
    extra = len(pages) - _PAGES_SHOWN
    if extra > 0:
        rows += (f'<tr class="more"><td colspan="2">'
                 f'{_esc(labels["pages_more"].format(count=extra))}</td></tr>')
    return (f'<section class="pages"><h2>{_esc(labels["pages_examined"])} '
            f'({len(pages)})</h2>'
            f'<table class="category-table pages-table">'
            f'<tr><th>{_esc(labels["page_col"])}</th>'
            f'<th class="num">{_esc(labels["count"])}</th></tr>'
            f'{rows}</table></section>')


def _top_patterns_section(model: ReportModel, labels: dict) -> str:
    """The highest-scoring passages, kept as detail rather than as a summary.

    The confidence tally that used to head this section now lives in the one
    "what was found" table; what is left here is the part that cannot go in a
    tally - the actual text, and why it scored.
    """
    ai = model.ai_patterns or {}
    top = ai.get("top_patterns") or []
    if not top:
        return ""
    rows = []
    for p in top:
        explanation = _esc(p.get("explanation", "")[:80])
        # A repo path is not a fifth column - most reports have none to show,
        # and a column empty in every row but a few reads as a layout defect
        # rather than as "this one is different". It rides inside the
        # explanation cell instead, on its own line, only where it exists.
        if p.get("source_file"):
            note = labels["source_at"].format(
                path=p["source_file"], line=p.get("source_line", 0))
            explanation += f'<div class="src">{_esc(note)}</div>'
        rows.append(
            f'<tr><td class="num">{p.get("score", 0):.2f}</td>'
            f'<td>{_esc(p.get("confidence", ""))}</td>'
            f'<td>{_esc(p.get("text", "")[:80])}</td>'
            f'<td>{explanation}</td></tr>')
    coverage = ""
    if ai.get("repo_total"):
        note = labels["repo_coverage"].format(
            matched=ai.get("repo_matched", 0), total=ai["repo_total"])
        coverage = f'<p class="repo-coverage">{_esc(note)}</p>'
    return (f'<section class="ai-patterns"><h2>{_esc(labels["top_patterns"])}'
            f'</h2>{coverage}<table class="category-table">'
            f'<tr><th class="num">{_esc(labels["score"])}</th>'
            f'<th>{_esc(labels["confidence"])}</th>'
            f'<th>{_esc(labels["text"])}</th>'
            f'<th>{_esc(labels["explanation"])}</th></tr>{"".join(rows)}</table></section>')


def render_html(model: ReportModel, lang: str = "en") -> str:
    """`ReportModel` -> a complete `<html>` document, ready for a browser or
    for `report.pdf.render_pdf`.

    Always the light `Palette`: the report is paper (or a PDF standing in
    for paper), and dark-mode colours that read well on a screen are the
    wrong contrast on white — see the module docstring.
    """
    if lang not in _LABELS:
        lang = "en"
    labels = _labels(lang)
    palette = palettes()["light"]

    # Grouped, not raw: one card per distinct problem, carrying every place
    # it was found. A thirty-page crawl of a site with a shared header used
    # to print the header's every fault thirty times. See
    # `ReportModel.grouped_findings`.
    findings = model.grouped_findings()
    by_severity: dict = {}
    by_category: dict = {}
    for finding in findings:
        by_severity[finding.severity] = by_severity.get(finding.severity, 0) + 1
        by_category[finding.category] = by_category.get(finding.category, 0) + 1
    mode_label = labels["mode"].get(model.meta.mode, model.meta.mode)
    logo = _logo_data_uri()

    stat_cards = []
    for rank in range(4):
        names = [name for name, r in
                 (("critical", 0), ("high", 0), ("serious", 1), ("medium", 1),
                  ("moderate", 2), ("low", 2), ("minor", 3))
                 if r == rank]
        count = sum(by_severity.get(name, 0) for name in names)
        if count == 0 and rank not in (0,):
            continue
        label = _SEVERITY_LABEL[rank].get(lang, _SEVERITY_LABEL[rank]["en"])
        accent = {0: palette.error, 1: palette.amber, 2: palette.amber,
                 3: palette.text_muted}[rank]
        stat_cards.append(_stat_card(count, label, palette, accent))

    # One table, not four. The category counts, the AI-pattern confidence
    # bands and the character tallies were three tables in three sections
    # separated by the findings, so a reader asking "what kind of thing did
    # this find" had to hold three places at once and never saw them beside
    # each other. They answer the same question and now sit in one answer.
    what_rows = _what_was_found(model, by_category, labels)

    charts = _charts(by_severity, by_category, labels, palette, lang)

    findings_html = ("".join(_finding_card(f, lang, palette) for f in findings)
                     if findings else f'<p class="empty">{_esc(labels["no_findings"])}</p>')

    pages_section = _pages_section(model, labels)
    ai_section = _top_patterns_section(model, labels)
    typo_section = ""

    doc_title = f'{labels["title"]} — {model.meta.target}' if model.meta.target else labels["title"]

    style = f"""
@page {{ size: A4; margin: 16mm 14mm; }}
* {{ box-sizing: border-box; }}
html, body {{ margin: 0; padding: 0; }}
body {{
  font-family: '{palette.font}', Arial, sans-serif;
  font-size: 10.5pt; line-height: 1.5;
  color: {palette.text}; background: {palette.bg};
}}
a {{ color: {palette.accent}; }}
h1, h2, h3 {{ font-family: '{palette.font}', Arial, sans-serif; color: {palette.text}; }}
.report-header {{
  display: flex; align-items: center; gap: 6mm;
  border-bottom: 1px solid {palette.border}; padding-bottom: 5mm; margin-bottom: 8mm;
}}
.report-header img {{ width: 22mm; height: auto; flex: 0 0 auto; }}
.report-header h1 {{ font-size: 17pt; margin: 0 0 1.5mm; overflow-wrap: anywhere; }}
.report-header .meta {{ margin: 0; font-size: 9pt; color: {palette.text_muted}; }}
/* Not `break-inside: avoid` any more. The overview now carries charts and a
   table and is taller than it was; forbidding a break inside it meant that
   whenever it did not fit in what was left of page one, the whole block
   jumped to page two and left most of page one blank. It may break; its
   headings may not be stranded, which is what the rules below say. */
.summary {{ margin-bottom: 9mm; }}
.summary h2 {{ font-size: 12pt; margin: 0 0 3mm; }}
h2, h3 {{ break-after: avoid; page-break-after: avoid; }}
.table-title {{ font-size: 10pt; margin: 6mm 0 2mm; color: {palette.text_muted};
  text-transform: uppercase; letter-spacing: .05em; }}

/* Charts: plain CSS bars, no script and no image, because `printToPdf` is
   the consumer and anything else sometimes prints blank. */
.charts {{ display: flex; gap: 8mm; margin: 4mm 0 2mm; }}
.chart {{ flex: 1 1 0; min-width: 0; break-inside: avoid; }}
.chart h3 {{ font-size: 8.5pt; margin: 0 0 2mm; color: {palette.text_muted};
  text-transform: uppercase; letter-spacing: .05em; font-weight: 600; }}
.bar-row {{ display: flex; align-items: center; gap: 2mm; margin: 1.2mm 0;
  font-size: 8.3pt; break-inside: avoid; }}
.bar-label {{ flex: 0 0 26mm; color: {palette.text_muted};
  overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }}
.bar-track {{ flex: 1 1 auto; height: 3mm; background: {palette.bg_muted};
  border-radius: 999px; overflow: hidden; }}
.bar-fill {{ display: block; height: 100%; border-radius: 999px; }}
.bar-num {{ flex: 0 0 auto; font-variant-numeric: tabular-nums;
  font-weight: 600; min-width: 9mm; text-align: right; }}
.stat-grid {{ display: flex; flex-wrap: wrap; gap: 4mm; margin-bottom: 5mm; }}
.stat-card {{
  flex: 1 1 26mm; border: 1px solid {palette.border}; border-radius: {palette.radius_md}px;
  padding: 3mm 4mm; text-align: center; background: {palette.bg_card};
}}
.stat-card .num {{ font-size: 17pt; font-weight: 700; }}
.stat-card .label {{
  font-size: 7.5pt; color: {palette.text_muted}; text-transform: uppercase; letter-spacing: .04em;
}}
table.category-table {{ width: 100%; border-collapse: collapse; font-size: 9pt; }}
table.category-table th, table.category-table td {{
  text-align: left; padding: 1.6mm 2mm; border-bottom: 1px solid {palette.border};
  vertical-align: top;
}}
table.category-table th {{ color: {palette.text_muted}; font-weight: 600; }}
/* A row may not be split across pages; the table may. The header repeats on
   each page it continues onto, so a table that spans a break stays readable. */
table.category-table tr {{ break-inside: avoid; page-break-inside: avoid; }}
table.category-table thead {{ display: table-header-group; }}
table.category-table td.num, table.category-table th.num {{
  text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap;
}}
table.find-table td.detail {{ color: {palette.text_muted}; }}
/* The repo path rides inside the explanation cell rather than its own
   column - see `_top_patterns_section` - so it needs to read as an aside,
   not as more of the explanation. */
table.category-table .src {{
  color: {palette.text_muted}; font-size: 8pt; margin-top: 1mm;
  font-family: ui-monospace, "SF Mono", Menlo, Consolas, monospace;
}}
.repo-coverage {{ color: {palette.text_muted}; font-size: 9pt; margin: -1mm 0 2mm; }}
/* The index of what was examined is context, not content: small type, and a
   fixed narrow column for the count so the addresses get the width. */
table.pages-table {{ font-size: 8pt; }}
table.pages-table td {{ padding: 1mm 2mm; overflow-wrap: anywhere; }}
table.pages-table tr.more td {{ color: {palette.text_muted}; font-style: italic; }}
.findings h2 {{ font-size: 12pt; margin: 0 0 4mm; }}
/* Cards may break across pages. Forbidding it is what left large blank areas:
   a tall card that did not fit in the remainder of a page moved to the next
   one whole, and the space it vacated stayed empty. What actually has to hold
   is that a card's heading is never the last thing on a page and a stray line
   never opens one - which is what `break-after` above and orphans/widows here
   say, without wasting a third of every page to say it. */
.finding {{
  break-inside: auto; orphans: 3; widows: 3;
  border: 1px solid {palette.border}; border-radius: {palette.radius_md}px;
  padding: 4.5mm 5.5mm; margin-bottom: 4.5mm; background: {palette.bg_card};
}}
.finding h3 {{ font-size: 10.8pt; margin: 0 0 1.5mm; overflow-wrap: anywhere;
  break-after: avoid; page-break-after: avoid; }}
.finding .location {{
  font-size: 8.3pt; color: {palette.text_muted}; margin: 0 0 3mm; overflow-wrap: anywhere;
}}
.finding ul.locations {{
  margin: -1.5mm 0 3mm; padding-left: 5mm; font-size: 8.3pt;
  color: {palette.text_muted}; list-style: disc;
}}
.finding ul.locations li {{ overflow-wrap: anywhere; margin: 0.3mm 0; }}
.finding ul.locations li.more {{ list-style: none; margin-left: -3mm; font-style: italic; }}
.finding-badges {{ margin-bottom: 2.5mm; }}
.badge {{
  display: inline-block; padding: .6mm 2.4mm; border-radius: 999px; font-size: 7.3pt;
  font-weight: 600; text-transform: uppercase; letter-spacing: .03em; margin-right: 1.5mm;
}}
.badge-outline {{ border: 1px solid {palette.border_strong}; color: {palette.text_muted}; }}
{_severity_css(palette)}
/* Small blocks stay whole: these are short, so keeping them together costs
   a line or two of slack rather than a third of a page. */
.field {{ margin: 2mm 0; break-inside: avoid; }}
.field .label {{
  font-weight: 600; font-size: 8.2pt; color: {palette.text_muted};
  text-transform: uppercase; letter-spacing: .03em; margin-bottom: .8mm;
}}
.field .value {{ font-size: 9.6pt; overflow-wrap: anywhere; }}
pre.snippet {{
  font-family: '{palette.font_mono}', 'Courier New', monospace; font-size: 8.4pt;
  white-space: pre-wrap; overflow-wrap: anywhere; word-break: break-word;
  background: {palette.bg_muted}; border: 1px solid {palette.border};
  border-radius: {palette.radius_sm}px; padding: 2mm 3mm; margin: 0;
}}
.wcag {{ font-size: 8pt; color: {palette.text_muted}; margin: 1.5mm 0 0; }}
.empty {{ color: {palette.text_muted}; }}
footer {{
  margin-top: 8mm; padding-top: 3mm; border-top: 1px solid {palette.border};
  font-size: 7.8pt; color: {palette.text_muted}; text-align: center;
}}
""".strip()

    logo_img = f'<img src="{logo}" alt="">' if logo else ""

    return f"""<!doctype html>
<html lang="{_esc(lang)}">
<head>
<meta charset="utf-8">
<title>{_esc(doc_title)}</title>
<style>{style}</style>
</head>
<body>
<header class="report-header">
  {logo_img}
  <div>
    <h1>{_esc(model.meta.target or labels["title"])}</h1>
    <p class="meta">{_esc(mode_label)} &middot; {_esc(labels["generated"])} {_esc(model.meta.generated_at)}</p>
  </div>
</header>

<section class="summary">
  <h2>{_esc(labels["overview"])}</h2>
  <div class="stat-grid">{"".join(stat_cards)}</div>
  {charts}
  <h3 class="table-title">{_esc(labels["what_found"])}</h3>
  {what_rows}
</section>

{ai_section}
{typo_section}

<section class="findings">
  <h2>{_esc(labels["findings"])} ({len(findings)})</h2>
  {findings_html}
</section>

{pages_section}

<footer>{_esc(labels["footer"])}</footer>
</body>
</html>
"""
