"""`ReportModel` -> a self-contained, print-ready HTML document.

Follows the same three print-CSS principles xFormat's own HTML export uses
(`apps/web/src/features/cv/cvHtmlTemplate.ts` in the `xformat` checkout,
read for the pattern only — it is a TypeScript/React template, nothing from
it is imported here):

* `@page { size: A4; margin: ... }` — real page geometry, not a CSS
  approximation of one. Unlike that template (which renders one continuous
  virtual page and lets a canvas-slicing pipeline carve it into PDF pages
  after the fact), this HTML is handed to `QWebEnginePage.printToPdf`
  directly — Chromium's own print pipeline paginates the flowing content,
  the same way "Print -> Save as PDF" does in a browser. So the page margin
  is declared once, in `@page`, and nothing here re-adds it as padding.
* `break-inside: avoid` on every finding card, so a card is never split
  across a page boundary.
* mm/pt units throughout — a print document, not a screen one.

Colours and type come from `ui.tokens.Palette`, always the **light** theme:
the report is meant to be printed or read as a document, and a dark card on
white paper is illegible on a real printer — see `render_html`'s `lang`
default and the light-only choice below.
"""
from __future__ import annotations

import base64
import html
from pathlib import Path

from report.model import CATEGORY_AI_TEXT, ReportModel
from ui.tokens import Palette, palettes

#: Vendored alongside the app icon — see `ui/main_window.py`'s `ASSETS`.
#: Reading it from here rather than reaching into a sibling `xformat`
#: checkout (which may not exist on the machine building the report) keeps
#: the report generator, like the desktop app itself, buildable from this
#: repository alone.
_LOGO_PATH = Path(__file__).resolve().parent.parent / "ui" / "design" / "assets" / "logo-light.svg"

#: Minimal, self-contained labels for the report's own chrome. Not routed
#: through `i18n.translations.t()`: this package does not touch that module
#: (see the repository's task boundary), and a report has a small, fixed
#: vocabulary of its own rather than the UI's much larger one.
_LABELS = {
    "en": dict(
        title="Scan report", generated="Generated", target="Target",
        summary="Summary", by_severity="By severity", by_category="By category",
        findings="Findings", no_findings="No findings — nothing to report.",
        category="Category", count="Count", found="Found", why="Why it matters",
        fix="How to fix", replacement="Ready replacement", engine="Detected by",
        wcag="WCAG", footer="Generated by AI Content Scanner.",
        mode={"text-web": "AI-text scan · website", "text-repo": "AI-text scan · repository",
             "audit-web": "Site audit · website", "audit-repo": "Site audit · repository",
             "audit-file": "Site audit · page"},
        cat={"ai-text": "AI-sounding text", "accessibility": "Accessibility",
            "performance": "Performance", "seo": "SEO", "best-practices": "Best practices"},
    ),
    "uk": dict(
        title="Звіт сканування", generated="Створено", target="Ціль",
        summary="Зведення", by_severity="За тяжкістю", by_category="За категорією",
        findings="Знахідки", no_findings="Знахідок немає — звітувати нема про що.",
        category="Категорія", count="Кількість", found="Що знайдено", why="Чому це важливо",
        fix="Як виправити", replacement="Готова заміна", engine="Знайшов",
        wcag="WCAG", footer="Згенеровано AI Content Scanner.",
        mode={"text-web": "Аналіз тексту · сайт", "text-repo": "Аналіз тексту · репозиторій",
             "audit-web": "Аудит доступності · сайт", "audit-repo": "Аудит доступності · репозиторій",
             "audit-file": "Аудит доступності · сторінка"},
        cat={"ai-text": "Схоже на текст ШІ", "accessibility": "Доступність",
            "performance": "Продуктивність", "seo": "SEO", "best-practices": "Найкращі практики"},
    ),
    "it": dict(
        title="Report di scansione", generated="Generato", target="Destinazione",
        summary="Riepilogo", by_severity="Per gravità", by_category="Per categoria",
        findings="Rilievi", no_findings="Nessun rilievo: niente da segnalare.",
        category="Categoria", count="Conteggio", found="Cosa è stato trovato",
        why="Perché è importante", fix="Come correggere", replacement="Sostituzione pronta",
        engine="Rilevato da", wcag="WCAG", footer="Generato da AI Content Scanner.",
        mode={"text-web": "Analisi testo · sito", "text-repo": "Analisi testo · repository",
             "audit-web": "Audit di accessibilità · sito",
             "audit-repo": "Audit di accessibilità · repository",
             "audit-file": "Audit di accessibilità · pagina"},
        cat={"ai-text": "Testo dall'aspetto artificiale", "accessibility": "Accessibilità",
            "performance": "Prestazioni", "seo": "SEO", "best-practices": "Best practice"},
    ),
}

#: One CSS class per rank so a mixed report (there is no such run today, but
#: nothing stops one) still paints consistently: rank 0-3, clamped, covers
#: both severity vocabularies (see `report.model.SEVERITY_RANK`).
_SEVERITY_LABEL = {
    0: {"en": "Critical", "uk": "Критично", "it": "Critico"},
    1: {"en": "Serious", "uk": "Серйозно", "it": "Grave"},
    2: {"en": "Moderate", "uk": "Помірно", "it": "Moderato"},
    3: {"en": "Minor", "uk": "Незначно", "it": "Minore"},
}


def _labels(lang: str) -> dict:
    return _LABELS.get(lang, _LABELS["en"])


def _logo_data_uri() -> str:
    try:
        raw = _LOGO_PATH.read_bytes()
    except OSError:
        return ""
    encoded = base64.b64encode(raw).decode("ascii")
    return f"data:image/svg+xml;base64,{encoded}"


def _rgba(hex_color: str, alpha: float) -> str:
    """`#rrggbb` -> `rgba(r, g, b, alpha)`, for a tinted badge background."""
    text = hex_color.lstrip("#")
    if len(text) == 3:
        text = "".join(ch * 2 for ch in text)
    if len(text) != 6:
        return hex_color
    try:
        r, g, b = (int(text[i:i + 2], 16) for i in (0, 2, 4))
    except ValueError:
        return hex_color
    return f"rgba({r}, {g}, {b}, {alpha})"


def _esc(value) -> str:
    """Escape anything interpolated into the document. Applied even to
    fields that are normally plain prose (a rule's `why`/`fix` text can
    still carry a raw `<` or `&` when it quotes an attribute value or a
    URL), and always to `snippet`/`replacement`, which are markup or code
    shown *as text* — never rendered as markup, per the task's escaping
    requirement."""
    return html.escape(str(value or ""), quote=True)


def _severity_css(palette: Palette) -> str:
    tiers = {
        0: (palette.error, _rgba(palette.error, 0.10)),
        1: (palette.amber, _rgba(palette.amber, 0.14)),
        2: (palette.amber, _rgba(palette.amber, 0.08)),
        3: (palette.text_muted, palette.bg_muted),
    }
    rules = []
    for rank, (fg, bg) in tiers.items():
        rules.append(
            f".sev-{rank} {{ color: {fg}; background: {bg}; }}\n"
            f".finding.sev-{rank} {{ border-left: 1.2mm solid {fg}; }}"
        )
    return "\n".join(rules)


def _stat_card(count: int, label: str, palette: Palette, accent: str | None = None) -> str:
    color = f"color: {accent};" if accent else ""
    return (
        f'<div class="stat-card"><div class="num" style="{color}">{count}</div>'
        f'<div class="label">{_esc(label)}</div></div>'
    )


def _finding_card(finding, lang: str, palette: Palette) -> str:
    labels = _labels(lang)
    rank = min(max(finding.severity_rank, 0), 3)
    severity_label = _SEVERITY_LABEL[rank].get(lang, _SEVERITY_LABEL[rank]["en"])
    category_label = labels["cat"].get(finding.category, finding.category)
    parts = [
        f'<article class="finding sev-{rank}">',
        '<div class="finding-badges">',
        f'<span class="badge sev-{rank}">{_esc(severity_label)}</span>',
        f'<span class="badge badge-outline">{_esc(category_label)}</span>',
    ]
    if finding.engine:
        parts.append(f'<span class="badge badge-outline">{_esc(finding.engine)}</span>')
    parts.append('</div>')
    parts.append(f'<h3>{_esc(finding.title)}</h3>')
    parts.append(f'<p class="location">{_esc(finding.location)}</p>')

    if finding.category == CATEGORY_AI_TEXT:
        if finding.why:
            parts.append(_field(labels["why"], finding.why, escape=True))
        if finding.snippet:
            parts.append(_field_pre(labels["found"], finding.snippet))
        if finding.replacement:
            parts.append(_field_pre(labels["replacement"], finding.replacement))
    else:
        if finding.found:
            parts.append(_field(labels["found"], finding.found, escape=True))
        if finding.why:
            parts.append(_field(labels["why"], finding.why, escape=True))
        if finding.fix:
            parts.append(_field(labels["fix"], finding.fix, escape=True))
        if finding.snippet:
            parts.append(_field_pre(labels["found"] + " —", finding.snippet))
        if finding.replacement:
            parts.append(_field_pre(labels["replacement"], finding.replacement))
        if finding.wcag:
            parts.append(
                f'<p class="wcag">{_esc(labels["wcag"])}: '
                f'{_esc(", ".join(finding.wcag))}</p>')

    parts.append('</article>')
    return "\n".join(parts)


def _field(label: str, value: str, escape: bool) -> str:
    body = _esc(value) if escape else value
    return (f'<div class="field"><div class="label">{_esc(label)}</div>'
            f'<div class="value">{body}</div></div>')


def _field_pre(label: str, value: str) -> str:
    return (f'<div class="field"><div class="label">{_esc(label)}</div>'
            f'<pre class="snippet">{_esc(value)}</pre></div>')


def render_html(model: ReportModel, lang: str = "en") -> str:
    """`ReportModel` -> a complete `<html>` document, ready for a browser or
    for `report.pdf.render_pdf`.

    Always the light `Palette`: the report is paper (or a PDF standing in
    for paper), and dark-mode colours that read well on a screen are the
    wrong contrast on white — see the module docstring.
    """
    if lang not in _LABELS:
        lang = "en"
    labels = _labels(lang)
    palette = palettes()["light"]

    findings = model.sorted_findings()
    by_severity = model.counts_by_severity()
    by_category = model.counts_by_category()
    mode_label = labels["mode"].get(model.meta.mode, model.meta.mode)
    logo = _logo_data_uri()

    stat_cards = []
    for rank in range(4):
        names = [name for name, r in
                 (("critical", 0), ("high", 0), ("serious", 1), ("medium", 1),
                  ("moderate", 2), ("low", 2), ("minor", 3))
                 if r == rank]
        count = sum(by_severity.get(name, 0) for name in names)
        if count == 0 and rank not in (0,):
            continue
        label = _SEVERITY_LABEL[rank].get(lang, _SEVERITY_LABEL[rank]["en"])
        accent = {0: palette.error, 1: palette.amber, 2: palette.amber,
                 3: palette.text_muted}[rank]
        stat_cards.append(_stat_card(count, label, palette, accent))

    category_rows = "".join(
        f'<tr><td>{_esc(labels["cat"].get(cat, cat))}</td><td>{count}</td></tr>'
        for cat, count in sorted(by_category.items(), key=lambda kv: -kv[1])
    )

    findings_html = ("".join(_finding_card(f, lang, palette) for f in findings)
                     if findings else f'<p class="empty">{_esc(labels["no_findings"])}</p>')

    doc_title = f'{labels["title"]} — {model.meta.target}' if model.meta.target else labels["title"]

    style = f"""
@page {{ size: A4; margin: 16mm 14mm; }}
* {{ box-sizing: border-box; }}
html, body {{ margin: 0; padding: 0; }}
body {{
  font-family: '{palette.font}', Arial, sans-serif;
  font-size: 10.5pt; line-height: 1.5;
  color: {palette.text}; background: {palette.bg};
}}
a {{ color: {palette.accent}; }}
h1, h2, h3 {{ font-family: '{palette.font}', Arial, sans-serif; color: {palette.text}; }}
.report-header {{
  display: flex; align-items: center; gap: 6mm;
  border-bottom: 1px solid {palette.border}; padding-bottom: 5mm; margin-bottom: 8mm;
}}
.report-header img {{ width: 22mm; height: auto; flex: 0 0 auto; }}
.report-header h1 {{ font-size: 17pt; margin: 0 0 1.5mm; overflow-wrap: anywhere; }}
.report-header .meta {{ margin: 0; font-size: 9pt; color: {palette.text_muted}; }}
.summary {{ break-inside: avoid; margin-bottom: 9mm; }}
.summary h2 {{ font-size: 12pt; margin: 0 0 3mm; }}
.stat-grid {{ display: flex; flex-wrap: wrap; gap: 4mm; margin-bottom: 5mm; }}
.stat-card {{
  flex: 1 1 26mm; border: 1px solid {palette.border}; border-radius: {palette.radius_md}px;
  padding: 3mm 4mm; text-align: center; background: {palette.bg_card};
}}
.stat-card .num {{ font-size: 17pt; font-weight: 700; }}
.stat-card .label {{
  font-size: 7.5pt; color: {palette.text_muted}; text-transform: uppercase; letter-spacing: .04em;
}}
table.category-table {{ width: 100%; border-collapse: collapse; font-size: 9pt; }}
table.category-table th, table.category-table td {{
  text-align: left; padding: 1.6mm 2mm; border-bottom: 1px solid {palette.border};
}}
table.category-table th {{ color: {palette.text_muted}; font-weight: 600; }}
.findings h2 {{ font-size: 12pt; margin: 0 0 4mm; }}
.finding {{
  break-inside: avoid; border: 1px solid {palette.border}; border-radius: {palette.radius_md}px;
  padding: 4.5mm 5.5mm; margin-bottom: 4.5mm; background: {palette.bg_card};
}}
.finding h3 {{ font-size: 10.8pt; margin: 0 0 1.5mm; overflow-wrap: anywhere; }}
.finding .location {{
  font-size: 8.3pt; color: {palette.text_muted}; margin: 0 0 3mm; overflow-wrap: anywhere;
}}
.finding-badges {{ margin-bottom: 2.5mm; }}
.badge {{
  display: inline-block; padding: .6mm 2.4mm; border-radius: 999px; font-size: 7.3pt;
  font-weight: 600; text-transform: uppercase; letter-spacing: .03em; margin-right: 1.5mm;
}}
.badge-outline {{ border: 1px solid {palette.border_strong}; color: {palette.text_muted}; }}
{_severity_css(palette)}
.field {{ margin: 2mm 0; }}
.field .label {{
  font-weight: 600; font-size: 8.2pt; color: {palette.text_muted};
  text-transform: uppercase; letter-spacing: .03em; margin-bottom: .8mm;
}}
.field .value {{ font-size: 9.6pt; overflow-wrap: anywhere; }}
pre.snippet {{
  font-family: '{palette.font_mono}', 'Courier New', monospace; font-size: 8.4pt;
  white-space: pre-wrap; overflow-wrap: anywhere; word-break: break-word;
  background: {palette.bg_muted}; border: 1px solid {palette.border};
  border-radius: {palette.radius_sm}px; padding: 2mm 3mm; margin: 0;
}}
.wcag {{ font-size: 8pt; color: {palette.text_muted}; margin: 1.5mm 0 0; }}
.empty {{ color: {palette.text_muted}; }}
footer {{
  margin-top: 8mm; padding-top: 3mm; border-top: 1px solid {palette.border};
  font-size: 7.8pt; color: {palette.text_muted}; text-align: center;
}}
""".strip()

    logo_img = f'<img src="{logo}" alt="">' if logo else ""

    return f"""<!doctype html>
<html lang="{_esc(lang)}">
<head>
<meta charset="utf-8">
<title>{_esc(doc_title)}</title>
<style>{style}</style>
</head>
<body>
<header class="report-header">
  {logo_img}
  <div>
    <h1>{_esc(model.meta.target or labels["title"])}</h1>
    <p class="meta">{_esc(mode_label)} &middot; {_esc(labels["generated"])} {_esc(model.meta.generated_at)}</p>
  </div>
</header>

<section class="summary">
  <h2>{_esc(labels["summary"])}</h2>
  <div class="stat-grid">{"".join(stat_cards)}</div>
  <table class="category-table">
    <tr><th>{_esc(labels["category"])}</th><th>{_esc(labels["count"])}</th></tr>
    {category_rows}
  </table>
</section>

<section class="findings">
  <h2>{_esc(labels["findings"])} ({len(findings)})</h2>
  {findings_html}
</section>

<footer>{_esc(labels["footer"])}</footer>
</body>
</html>
"""
