"""What technology a directory is, and what that means for reading it.

Every exclusion this tool has was added after a false-positive class turned
up in someone's project: `.tsx` skipped and then un-skipped (`P-19`), PHP
masked (three WordPress themes), `wp-admin/` excluded (455 findings in
vendored WordPress core). Each was correct and each was reactive, which means
the next stack fails the same way before anyone notices.

That is the thing this module fixes. A repository announces what it is -
`wp-config.php`, `artisan`, `next.config.js`, `manage.py` - and what it is
decides two things a scan otherwise has to guess:

* **what is not the product.** `vendor/` in a Laravel app, `wp-includes/` in
  a WordPress install and `.svelte-kit/` in a SvelteKit app are all code
  somebody else wrote or a build step emitted. Auditing them reports real
  defects against files the developer cannot change, which buries the ones
  they can.
* **what the markup is written in.** A `.php` file is a template with server
  tags; a `.tsx` file is JSX. Both need masking before an HTML parser sees
  them, and the masks differ.

Two rules hold everything here honest:

**Detection is evidence, never a guess.** A profile names the file that
proved it, and `Profile.evidence` travels into the report. A stack nobody can
point at a marker file for is simply not detected, and the scan falls back to
the defaults - which is the behaviour that already worked.

**An exclusion must be about ownership, not about names.** `dist/` earns its
place because a bundler wrote it. A directory is never excluded for looking
unimportant: `repo_scanner`'s own comment records that guessing at `lib/`
blinded the scanner to 67 real findings in xFormat.
"""
from __future__ import annotations

import json
import re
from re import error
from dataclasses import dataclass, field
from pathlib import Path

#: Files whose first lines say a machine wrote them. Checked ahead of any
#: stack, because the marker is a convention rather than a technology:
#: protobuf, GraphQL codegen, OpenAPI clients, Prisma, i18n extractors and
#: `.d.ts` emitters all write one, and none of them is a file anyone edits.
#:
#: A finding in a generated file is not wrong, it is unactionable - the fix
#: belongs in the generator, and the file is overwritten on the next build.
_GENERATED_MARKERS = (
    "do not edit",
    "do not modify",
    "auto-generated",
    "autogenerated",
    "automatically generated",
    "generated by",
    "@generated",
    "code generated by",
)
#: How far into a file to look for one. Every convention puts the marker in a
#: header comment; scanning further would read whole files to find a phrase
#: that legitimately appears in prose.
_GENERATED_HEAD = 600


def looks_generated(text: str) -> bool:
    """Does this file say a machine wrote it?

    Deliberately narrow: the marker has to be near the top, where every
    generator convention puts it. A README that discusses generated code
    mentions the phrase in its body and is not caught.
    """
    head = text[:_GENERATED_HEAD].lower()
    return any(marker in head for marker in _GENERATED_MARKERS)


@dataclass(frozen=True)
class Stack:
    """One technology, and what reading it implies."""
    name: str
    #: What proves this stack. An entry is either one path, or a tuple of
    #: paths that must **all** be present.
    #:
    #: The tuple form exists because some marker names are not owned by their
    #: stack. `config.toml` is Hugo's, and also Supabase's: on this machine
    #: `xformat-backend/supabase/config.toml` identified a Node backend as a
    #: Hugo site, which would have excluded its `public/` directory - real
    #: source, hidden by a wrong guess. A generic name has to be corroborated
    #: by something only the real stack has.
    markers: tuple = ()
    #: `(path, regex)` pairs where the *content* is the marker. Some stacks
    #: are not identified by a file name at all: a WordPress theme is a
    #: folder whose `style.css` carries a `Theme Name:` header, and a plugin
    #: is a PHP file with `Plugin Name:` in its opening comment. That is not
    #: a convention this tool invented - it is how WordPress itself finds
    #: them - and a marker list that only knows file names cannot see it.
    #: A `*` in the path globs; the regex is searched in the first
    #: `_CONTENT_MARKER_BYTES` of each match.
    content_markers: tuple = ()
    #: Gitignore-style patterns for what this stack vendors or generates.
    excludes: tuple = ()
    #: A one-line reason, printed beside the exclusions so a person can
    #: disagree with them.
    why: str = ""
    #: True when this is something a *served page* reveals rather than a
    #: checkout on disk. A hosted platform has no `vendor/` for anyone to
    #: exclude - what it has is a page whose markup says who built it, and
    #: that is worth knowing for a different reason: it tells a reader which
    #: findings belong to the platform rather than to them.
    hosted: bool = False


#: Ordered most specific first: a WordPress install is also a PHP project and
#: a Next.js app is also a Node one, and the narrower answer is the useful
#: one. Detection does not stop at the first match - a repository really can
#: be a Rails app with a Vite frontend - but the order decides what is
#: reported first.
STACKS = (
    # A theme and a plugin are handed over on their own far more often than
    # a whole installation is - that is what a contractor delivers - and
    # neither carries a single marker of the installation around it. They
    # are listed before `wordpress` so the more specific reading wins the
    # "reported first" position.
    Stack("wordpress-theme",
          content_markers=(("style.css", r"^\s*\**\s*Theme Name:\s*\S"),),
          excludes=("node_modules/", "vendor/", "dist/", "build/",
                    "assets/dist/"),
          why="a theme's own build output and vendored libraries; the theme "
              "itself is templates, and every one of them is a fragment of a "
              "page rather than a page"),
    Stack("wordpress-plugin",
          content_markers=(("*.php", r"^\s*\**\s*Plugin Name:\s*\S"),),
          excludes=("node_modules/", "vendor/", "dist/", "build/"),
          why="a plugin's build output and vendored libraries"),
    Stack("wordpress",
          markers=("wp-config.php", "wp-config-sample.php", "wp-load.php",
                   "wp-content", "wp-includes"),
          excludes=("wp-admin/", "wp-includes/", "wp-content/plugins/",
                    "wp-content/mu-plugins/", "wp-content/uploads/",
                    "wp-content/upgrade/", "wp-content/cache/",
                    "wp-content/themes/twenty*/"),
          why="WordPress core, bundled plugins and uploads are not this project's code"),
    Stack("drupal",
          markers=("core/lib/Drupal.php", "core/core.services.yml"),
          excludes=("core/", "modules/contrib/", "themes/contrib/",
                    "profiles/contrib/", "libraries/", "sites/*/files/"),
          why="Drupal core and contributed modules are upstream code"),
    Stack("joomla",
          markers=(("configuration.php", "libraries/src/Factory.php"),
                   "libraries/src/Factory.php"),
          excludes=("libraries/", "administrator/components/com_admin/",
                    "media/vendor/", "cache/"),
          why="Joomla core libraries are upstream code"),
    Stack("magento",
          markers=("bin/magento", "app/etc/di.xml"),
          excludes=("vendor/", "generated/", "pub/static/", "var/"),
          why="Magento generates pub/static and generated/ on every deploy"),
    Stack("laravel",
          markers=("artisan",),
          excludes=("vendor/", "storage/", "bootstrap/cache/",
                    "public/build/", "public/vendor/"),
          why="Composer packages and compiled Blade/asset output"),
    Stack("symfony",
          markers=("bin/console", "config/bundles.php"),
          excludes=("vendor/", "var/", "public/bundles/"),
          why="Composer packages and the Symfony cache"),
    Stack("django",
          markers=("manage.py",),
          excludes=("staticfiles/", "static_root/", "media/", "*/migrations/"),
          why="collectstatic output is a copy of files audited at their source"),
    Stack("rails",
          markers=("bin/rails", "config/application.rb"),
          excludes=("vendor/bundle/", "tmp/", "public/assets/",
                    "public/packs/", "log/"),
          why="bundled gems and the compiled asset pipeline"),
    Stack("nextjs",
          markers=("next.config.js", "next.config.mjs", "next.config.ts"),
          excludes=(".next/", "out/"),
          why="the Next.js build output"),
    Stack("nuxt",
          markers=("nuxt.config.js", "nuxt.config.ts"),
          excludes=(".nuxt/", ".output/"),
          why="the Nuxt build output"),
    Stack("astro",
          markers=("astro.config.mjs", "astro.config.ts", "astro.config.js"),
          excludes=("dist/", ".astro/"),
          why="the Astro build output"),
    Stack("sveltekit",
          markers=("svelte.config.js", "svelte.config.ts"),
          excludes=(".svelte-kit/", "build/"),
          why="the SvelteKit build output"),
    Stack("angular",
          markers=("angular.json",),
          excludes=("dist/", ".angular/"),
          why="the Angular build output"),
    Stack("gatsby",
          markers=("gatsby-config.js", "gatsby-config.ts"),
          excludes=("public/", ".cache/"),
          why="Gatsby writes public/ on every build"),
    Stack("hugo",
          markers=("hugo.toml", "hugo.yaml",
                   ("config.toml", "archetypes"),
                   ("config.toml", "layouts")),
          excludes=("public/", "resources/_gen/"),
          why="the Hugo build output"),
    Stack("jekyll",
          markers=(("_config.yml", "_layouts"), ("_config.yml", "_posts")),
          excludes=("_site/", ".jekyll-cache/", "vendor/bundle/"),
          why="the Jekyll build output"),
    Stack("spfx",
          markers=("config/package-solution.json",
                   # A single web part handed over without the solution
                   # around it: the class it extends is the marker, and it
                   # is in the file that defines the part.
                   "src/webparts", "*WebPart.ts", "*WebPart.tsx"),
          excludes=("lib/", "temp/", "sharepoint/solution/", "release/",
                    "ClientSideAssets/"),
          why="SPFx compiles TypeScript into lib/ and packages it into sharepoint/"),
    Stack("flutter",
          markers=("pubspec.yaml",),
          excludes=("build/", ".dart_tool/"),
          why="the Flutter build output"),
    Stack("vite",
          markers=("vite.config.js", "vite.config.ts", "vite.config.mjs"),
          excludes=("dist/",),
          why="the Vite build output"),
    Stack("remix",
          markers=("remix.config.js", "remix.config.ts"),
          excludes=("build/", "public/build/", ".cache/"),
          why="the Remix server and browser builds"),
    Stack("eleventy",
          markers=(".eleventy.js", "eleventy.config.js", "eleventy.config.mjs"),
          excludes=("_site/", ".cache/"),
          why="the Eleventy build output"),
    Stack("docusaurus",
          markers=("docusaurus.config.js", "docusaurus.config.ts"),
          excludes=("build/", ".docusaurus/"),
          why="the Docusaurus build output"),
    Stack("ember",
          markers=("ember-cli-build.js",),
          excludes=("dist/", "tmp/"),
          why="the Ember build output"),
    Stack("qwik",
          markers=(("vite.config.ts", "src/entry.ssr.tsx"),),
          excludes=("dist/", "server/"),
          why="the Qwik build output"),
    Stack("craft",
          markers=(("composer.json", "craft"),),
          excludes=("vendor/", "storage/", "web/cpresources/"),
          why="Composer packages and Craft's published control-panel assets"),
    Stack("statamic",
          markers=(("artisan", "content/collections"),),
          excludes=("vendor/", "storage/", "public/build/"),
          why="Composer packages and compiled Antlers assets"),
    Stack("shopify",
          markers=(("config/settings_schema.json", "layout/theme.liquid"),
                   "layout/theme.liquid"),
          excludes=("assets/*.min.*", "node_modules/"),
          why="Shopify themes ship minified assets beside their source"),
    Stack("dotnet",
          markers=("Program.cs", "Startup.cs"),
          excludes=("bin/", "obj/", "wwwroot/lib/", "wwwroot/dist/"),
          why="compiler output and vendored client libraries"),
    Stack("spring",
          markers=(("pom.xml", "src/main/resources/templates"),
                   ("build.gradle", "src/main/resources/templates")),
          excludes=("target/", "build/", "src/main/resources/static/vendor/"),
          why="Maven and Gradle build output"),
    Stack("wagtail",
          markers=(("manage.py", "home/models.py"),),
          excludes=("staticfiles/", "media/", "*/migrations/"),
          why="collectstatic output and uploaded media"),
    Stack("silverstripe",
          markers=(("composer.json", "app/_config"),),
          excludes=("vendor/", "public/resources/", "public/assets/"),
          why="Composer packages and published resources"),
    Stack("ghost",
          markers=(("package.json", "default.hbs"),
                   ("default.hbs", "partials"),
                   "routes.yaml"),
          excludes=("assets/built/", "node_modules/", "dist/"),
          why="a Ghost theme ships compiled assets beside its Handlebars source"),
    # --- platforms that exist only in served markup ------------------------
    #
    # No checkout, so nothing to exclude: what they have is a page whose shell
    # they built. Knowing that is worth something for a different reason -
    # a finding inside the parts a platform generates belongs to the platform,
    # not to whoever writes the content.
    Stack("wix", hosted=True,
          why="Wix builds and serves the page shell"),
    Stack("squarespace", hosted=True,
          why="Squarespace builds and serves the page shell"),
    Stack("webflow", hosted=True,
          why="Webflow publishes the page from its own builder"),
    Stack("beehiiv", hosted=True,
          why="beehiiv hosts the newsletter and its web archive"),
    Stack("carrd", hosted=True,
          why="Carrd hosts and renders the page"),
    Stack("typo3", hosted=True,
          why="TYPO3 renders the page server-side"),
    Stack("storybook",
          markers=(".storybook/main.js", ".storybook/main.ts"),
          excludes=("storybook-static/",),
          why="the built Storybook, which is documentation of the components audited at their source"),
)


#: What a served page reveals about what built it.
#:
#: Modelled on the method Wappalyzer's fingerprint set uses, because that set
#: has been maintained against the whole web for a decade and this one has
#: not: each signature carries a **confidence**, and a technology counts as
#: detected only when the signatures that matched add up to 100. A pattern
#: that could plausibly appear for another reason scores below 100 and has to
#: be corroborated; a pattern only one platform ever emits scores 100 on its
#: own.
#:
#: The version comes from a capture group where the markup carries one, for
#: the same reason the evidence names the file on disk: "WordPress" is a
#: guess someone has to verify, "WordPress 7.1" is a fact they can act on.
#:
#: This exists because a crawled site had **no** stack detection at all.
#: `detect()` reads marker files, and a URL has none, so a site scan knew
#: nothing about what it was reading while the same project on disk knew
#: everything. Measured on `phpstack-1451965-6319681.cloudwaysapps.com`:
#: `<meta name="generator" content="WordPress 7.1">` was in the markup the
#: whole time.


@dataclass(frozen=True)
class Signature:
    """One literal a platform emits, and how much it proves on its own."""
    stack: str
    pattern: str
    why: str
    #: Combined across every signature that matched; 100 means detected. A
    #: value below 100 says "this could be here for another reason".
    confidence: int = 100
    #: Which capture group holds the version, or 0 for none.
    version_group: int = 0


_SIGNATURES = (
    # --- generator metas: a platform writing its own name and version ------
    #
    # The quotes are optional in every one of these, and that is not
    # pedantry: HTML has always allowed an unquoted attribute value, and
    # `gohugo.io` - the Hugo project's own site - writes
    # `<meta name=generator content="Hugo 0.165.0">`. Requiring quotes around
    # the *name* made a whole class of pages invisible, and the first one
    # tried happened to be the one that would have embarrassed us most.
    Signature("wordpress", r'name=["\']?generator["\']?[^>]*content=["\']?WordPress[ /]?([\d.]*)',
              "generator meta", version_group=1),
    Signature("drupal", r'name=["\']?generator["\']?[^>]*content=["\']?Drupal[ /]?([\d.]*)',
              "generator meta", version_group=1),
    Signature("joomla", r'name=["\']?generator["\']?[^>]*content=["\']?Joomla',
              "generator meta"),
    Signature("typo3", r'name=["\']?generator["\']?[^>]*content=["\']?TYPO3',
              "generator meta"),
    Signature("hugo", r'name=["\']?generator["\']?[^>]*content=["\']?Hugo[ /]?([\d.]*)',
              "generator meta", version_group=1),
    Signature("jekyll", r'name=["\']?generator["\']?[^>]*content=["\']?Jekyll[ v]*([\d.]*)',
              "generator meta", version_group=1),
    Signature("ghost", r'name=["\']?generator["\']?[^>]*content=["\']?Ghost[ /]?([\d.]*)',
              "generator meta", version_group=1),
    Signature("astro", r'name=["\']?generator["\']?[^>]*content=["\']?Astro[ v]*([\d.]*)',
              "generator meta", version_group=1),
    Signature("gatsby", r'name=["\']?generator["\']?[^>]*content=["\']?Gatsby[ ]?([\d.]*)',
              "generator meta", version_group=1),
    Signature("docusaurus", r'name=["\']?generator["\']?[^>]*content=["\']?Docusaurus[ v]*([\d.]*)',
              "generator meta", version_group=1),
    Signature("craft", r'name=["\']?generator["\']?[^>]*content=["\']?Craft',
              "generator meta"),
    Signature("statamic", r'name=["\']?generator["\']?[^>]*content=["\']?Statamic',
              "generator meta"),
    Signature("silverstripe", r'name=["\']?generator["\']?[^>]*content=["\']?SilverStripe',
              "generator meta"),
    Signature("wix", r'name=["\']?generator["\']?[^>]*content=["\']?Wix\.com',
              "generator meta"),

    # --- asset hosts a platform owns ---------------------------------------
    Signature("wordpress", r'/wp-(?:content|includes)/', "wp-content asset path"),
    Signature("shopify", r'cdn\.shopify\.com|\.myshopify\.com', "Shopify CDN"),
    Signature("shopify", r'Shopify\.theme\b', "Shopify runtime object"),
    Signature("wix", r'static\.parastorage\.com|wixstatic\.com', "Wix asset host"),
    Signature("squarespace", r'assets\.squarespace\.com|static1\.squarespace\.com',
              "Squarespace asset host"),
    Signature("webflow", r'assets(?:-global)?\.website-files\.com|uploads-ssl\.webflow\.com',
              "Webflow asset host"),
    Signature("webflow", r'\sdata-wf-site=', "data-wf-site attribute"),
    Signature("beehiiv", r'cdn\.beehiiv\.com|beehiiv\.com/subscribe',
              "beehiiv CDN or subscribe endpoint"),
    Signature("carrd", r'\.carrd\.co/assets|cdn\.carrd\.co', "Carrd asset host"),

    # --- runtime payloads a framework injects ------------------------------
    Signature("nextjs", r'id=["\']__NEXT_DATA__["\']', "__NEXT_DATA__ payload"),
    Signature("nextjs", r'/_next/static/', "Next.js asset path"),
    Signature("nuxt", r'window\.__NUXT__', "__NUXT__ payload"),
    Signature("nuxt", r'/_nuxt/', "Nuxt asset path"),
    Signature("angular", r'\sng-version=["\']([\d.]+)', "ng-version attribute",
              version_group=1),
    Signature("sveltekit", r'/_app/immutable/', "SvelteKit asset path"),
    Signature("remix", r'window\.__remixContext', "__remixContext payload"),

    # --- signals that are real but could be there for another reason -------
    #
    # Below 100 on purpose. `ClientSideAssets` is SharePoint's convention and
    # also a plausible folder name anyone could pick; the literal `SPFx`
    # appears in prose about SharePoint as often as in a page built with it.
    # Neither is allowed to name a platform alone.
    Signature("spfx", r'/ClientSideAssets/', "ClientSideAssets path", confidence=60),
    Signature("spfx", r'\bSPFx\b', "the string SPFx", confidence=40),
    Signature("spfx", r'_spPageContextInfo', "SharePoint page context", confidence=100),
    # Ghost's own front end, but a theme can be lifted onto anything.
    Signature("ghost", r'/ghost/api/', "Ghost Content API path", confidence=70),
    Signature("ghost", r'\bgh-(?:head|foot|canvas)\b', "Ghost theme class", confidence=50),
)

_COMPILED = tuple(
    (sig, re.compile(sig.pattern, re.IGNORECASE)) for sig in _SIGNATURES
)

#: Combined confidence a stack has to reach before it is named.
_DETECTED_AT = 100


def _stack_by_name(name: str) -> Stack:
    for stack in STACKS:
        if stack.name == name:
            return stack
    return Stack(name, why="identified from the served markup", hosted=True)


def detect_from_markup(markup: str) -> Profile:
    """What a served page says built it, on signatures alone.

    A signature is a literal that platform emits - never an inference from
    layout, class names or "feel". Weak signatures accumulate: two 50s name a
    platform, one 50 does not. A page carrying nothing is undetected, which is
    what most hand-built sites are and what the scan already handles.

    Several platforms can be true at once and all are kept. A WordPress site
    served through Shopify's CDN is two facts, and picking one would throw the
    other away.
    """
    profile = Profile(root="")
    text = markup or ""
    scores: dict = {}
    reasons: dict = {}
    versions: dict = {}

    for sig, pattern in _COMPILED:
        match = pattern.search(text)
        if not match:
            continue
        scores[sig.stack] = scores.get(sig.stack, 0) + sig.confidence
        reasons.setdefault(sig.stack, []).append(sig.why)
        if sig.version_group and not versions.get(sig.stack):
            try:
                found = (match.group(sig.version_group) or "").strip()
            except (IndexError, error):
                found = ""
            if found:
                versions[sig.stack] = found

    for name, score in scores.items():
        if score < _DETECTED_AT:
            continue
        profile.stacks.append(_stack_by_name(name))
        evidence = " + ".join(reasons[name])
        if name in versions:
            evidence = f"{evidence} (version {versions[name]})"
        profile.evidence[name] = evidence
        profile.versions[name] = versions.get(name, "")
    return profile


#: Code a platform injects into the page **itself**, per stack. One test
#: decides membership, and it is not "did the author type this": it is
#: **can the site owner change it at all**.
#:
#: What this is for: a finding inside markup the platform generated is not the
#: site owner's to fix. A WordPress site is told about render-blocking
#: stylesheets, and they are `wp-includes/blocks/*/style.min.css`, enqueued by
#: core - the owner can no more remove them than they can edit someone else's
#: server. Reporting that as their problem is the report being technically
#: right and practically useless, which is how a tool trains people to skim.
#:
#: Every entry here was measured against a live site, and measuring is what
#: emptied most of the list:
#:
#: * **A CDN is not a platform.** `cdn.shopify.com` was in this table until a
#:   run on `shopify.com` attributed 20 findings to Shopify - most of them
#:   `<video>` elements with no captions, whose only Shopify-ness was where
#:   the poster image was hosted. A merchant's own uploads sit on that host
#:   too. Only `shopifycloud`, which is storefront code nobody can edit,
#:   survived. The same removed `static.wixstatic.com`, `media.beehiiv.com`
#:   and `website-files.com`.
#: * **A build is the author's.** `/_next/static/`, `/_nuxt/`,
#:   `/_app/immutable/` are the author's own code compiled, so Next, Nuxt and
#:   SvelteKit own nothing - and neither do Hugo, Jekyll, Astro, Vite or
#:   Eleventy, which is why no generator appears here at all. Detecting Hugo
#:   says something about the project; it says nothing about who owns a
#:   finding.
#: * **A theme is chosen and editable**, so `wp-content/themes/` is the
#:   owner's responsibility even when they did not type it. A plugin is
#:   chosen too, but its markup cannot be changed without forking it, so it
#:   stays here.
#:
#: Nothing is ever suppressed by this. The finding is reported either way -
#: a rule that removes a real finding makes a scan quieter and worse - and
#: what changes is only who is named as able to act on it.
PLATFORM_ASSETS: dict = {
    "wordpress": ("/wp-includes/", "/wp-content/plugins/", "/wp-json/",
                  "wp-emoji-release.min.js"),
    "drupal": ("/core/misc/", "/core/modules/", "/core/assets/"),
    "joomla": ("/media/jui/", "/media/system/js/"),
    "typo3": ("/typo3temp/", "/typo3conf/"),
    "shopify": ("shopifycloud",),
    "wix": ("static.parastorage.com",),
    "squarespace": ("assets.squarespace.com/universal",),
    "ghost": ("/public/cards.min.",),
    "spfx": ("/_layouts/15/",),
}


def platform_owner(stack_names, text: str) -> str:
    """Which detected platform emitted this markup, or `""` for the author.

    `text` is the offending markup itself, so the answer rests on the same
    kind of evidence the detection does: a literal path that is in the
    element or is not. An element carrying no address - a heading with a
    contrast problem, a field with no label - belongs to whoever wrote the
    page, which is the answer this returns by staying empty.
    """
    if not text:
        return ""
    haystack = text.lower()
    for name in stack_names:
        for fragment in PLATFORM_ASSETS.get(name, ()):
            if fragment.lower() in haystack:
                return name
    return ""


@dataclass
class Profile:
    """What a directory turned out to be."""
    root: str = ""
    stacks: list = field(default_factory=list)
    #: `stack name -> the marker path that proved it`. Kept so the report can
    #: say why a directory was skipped, and so a wrong answer is arguable
    #: rather than mysterious.
    evidence: dict = field(default_factory=dict)
    #: `stack name -> version`, where the markup carried one. "WordPress" is a
    #: guess someone has to verify; "WordPress 7.1" is a fact they can act on.
    versions: dict = field(default_factory=dict)

    def excludes(self) -> list:
        """Every stack's exclusions, in detection order, without repeats."""
        seen: list = []
        for stack in self.stacks:
            for pattern in stack.excludes:
                if pattern not in seen:
                    seen.append(pattern)
        return seen

    def applied_to(self, patterns) -> list:
        """`patterns`, plus this profile's exclusions, without repeats.

        One function rather than the same three lines in every surface. The
        CLI had them and the window did not, which is why a folder audited
        from the window walked into `wp-includes/` and reported hundreds of
        findings against code the developer cannot change, while the same
        folder audited from `xanalyze audit` did not.
        """
        merged = list(patterns or [])
        for pattern in self.excludes():
            if pattern not in merged:
                merged.append(pattern)
        return merged

    def describe(self) -> str:
        """One line for the run's own output. Empty when nothing matched."""
        if not self.stacks:
            return ""
        names = ", ".join(stack.name for stack in self.stacks)
        return f"detected: {names}"

    def reasons(self) -> list:
        return [f"{stack.name}: {stack.why} (found {self.evidence[stack.name]})"
                for stack in self.stacks if stack.name in self.evidence]


#: How far below the target to look for a marker. A monorepo keeps its
#: applications one or two levels down - `apps/web/vite.config.ts`,
#: `web/wp-config.php`, `trasparenza/composer.json` - and scanning the
#: repository root is the normal thing to do. Every real project on this
#: machine except one was invisible at depth 0.
#:
#: Bounded, and it has to be: an unbounded walk would find a marker inside a
#: fixture, a vendored copy or a test project and apply that stack's
#: exclusions to the whole repository. Two levels is what a monorepo layout
#: costs; anything deeper is somebody else's project living inside this one.
_MARKER_DEPTH = 2

#: Directories never searched for markers, because a marker found in one
#: describes something other than the project: a vendored dependency's own
#: config, or a fixture built to look like a stack.
_MARKER_BLIND = {"node_modules", "vendor", "dist", "build", "out", ".git",
                 ".next", ".nuxt", ".svelte-kit", "__pycache__", "venv",
                 ".venv", "fixtures", "__fixtures__", "testdata"}


def _search_roots(root: Path) -> list:
    """`root` and the directories under it worth looking in, nearest first."""
    roots = [root]
    frontier = [root]
    for _level in range(_MARKER_DEPTH):
        nxt = []
        for parent in frontier:
            try:
                children = sorted(p for p in parent.iterdir() if p.is_dir())
            except OSError:
                continue
            for child in children:
                if child.name in _MARKER_BLIND or child.name.startswith("."):
                    continue
                roots.append(child)
                nxt.append(child)
        frontier = nxt
    return roots


#: How much of a file is read looking for a content marker. The headers
#: these look for are the first thing in the file by definition - WordPress
#: itself only reads the first 8 KB of `style.css` - so anything past this
#: is not a header, it is a coincidence.
_CONTENT_MARKER_BYTES = 8192


def _content_marker_present(root: Path, marker) -> bool:
    """Is there a file here whose *content* proves this stack?"""
    import re as _re

    path_pattern, pattern = marker
    candidates = (sorted(root.glob(path_pattern))[:20] if "*" in path_pattern
                  else [root / path_pattern])
    expression = _re.compile(pattern, _re.M | _re.I)
    for candidate in candidates:
        try:
            if not candidate.is_file():
                continue
            head = candidate.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if expression.search(head[:_CONTENT_MARKER_BYTES]):
            return True
    return False


def _marker_present(root: Path, marker) -> bool:
    """Is this marker satisfied here? A tuple means every part must be."""
    if isinstance(marker, tuple):
        return all(_marker_present(root, part) for part in marker)
    if "*" in marker:
        return any(root.glob(marker))
    return (root / marker).exists()


def _content_marker_label(root: Path, base: Path, marker) -> str:
    """The evidence, as the file and the header that proved it."""
    path_pattern, pattern = marker
    header = pattern.strip("^\\s*").split(":")[0].replace("\\*", "").strip("\\s* ")
    if "*" in path_pattern:
        import re as _re

        expression = _re.compile(pattern, _re.M | _re.I)
        for candidate in sorted(root.glob(path_pattern))[:20]:
            try:
                if candidate.is_file() and expression.search(
                        candidate.read_text(encoding="utf-8",
                                            errors="replace")[:_CONTENT_MARKER_BYTES]):
                    path_pattern = candidate.name
                    break
            except OSError:
                continue
    try:
        where = str((root / path_pattern).relative_to(base))
    except ValueError:  # pragma: no cover - root is always under base
        where = path_pattern
    return f"{where} -> {header}:"


def _marker_label(root: Path, base: Path, marker) -> str:
    """How the evidence reads in the report."""
    if isinstance(marker, tuple):
        return " + ".join(_marker_label(root, base, part) for part in marker)
    try:
        return str((root / marker).relative_to(base))
    except ValueError:  # pragma: no cover - root is always under base
        return str(marker)


#: `package.json` dependency names that identify a stack whose config file may
#: be absent or renamed. Read only when the manifest parses; a broken
#: `package.json` is not evidence of anything.
_DEPENDENCY_STACKS = {
    "next": "nextjs", "nuxt": "nuxt", "astro": "astro",
    "@sveltejs/kit": "sveltekit", "@angular/core": "angular",
    "gatsby": "gatsby", "vite": "vite",
    "@microsoft/sp-core-library": "spfx",
}


def _dependency_names(root: Path) -> set:
    manifest = root / "package.json"
    if not manifest.is_file():
        return set()
    try:
        data = json.loads(manifest.read_text(encoding="utf-8", errors="replace"))
    except (json.JSONDecodeError, OSError):
        return set()
    names: set = set()
    for section in ("dependencies", "devDependencies"):
        block = data.get(section)
        if isinstance(block, dict):
            names.update(block)
    return names


def detect(root: str | Path) -> Profile:
    """What this directory is, on the evidence in it.

    Marker files first, then `package.json` dependencies for the JavaScript
    stacks - a Next.js app whose config file is `next.config.mjs` is caught
    by the marker, and one that has none is caught by the dependency. Both
    record what they saw.

    Never raises: an unreadable directory is simply an undetected one, and an
    undetected one scans exactly the way it did before this module existed.
    """
    path = Path(root)
    profile = Profile(root=str(path))
    if not path.is_dir():
        return profile

    roots = _search_roots(path)
    for stack in STACKS:
        proof = ""
        for where in roots:
            for marker in stack.markers:
                try:
                    if _marker_present(where, marker):
                        proof = _marker_label(where, path, marker)
                        break
                except (OSError, ValueError):
                    continue
            if proof:
                break
        if not proof:
            # Content markers, for a stack whose proof is inside a file
            # rather than in its name. See `Stack.content_markers`.
            for where in roots:
                for marker in stack.content_markers:
                    try:
                        if _content_marker_present(where, marker):
                            proof = _content_marker_label(where, path, marker)
                            break
                    except (OSError, ValueError):
                        continue
                if proof:
                    break
        if not proof:
            for where in roots:
                dependencies = _dependency_names(where)
                if not dependencies:
                    continue
                for name, stack_name in _DEPENDENCY_STACKS.items():
                    if stack_name == stack.name and name in dependencies:
                        try:
                            rel = str((where / "package.json").relative_to(path))
                        except ValueError:  # pragma: no cover - path is under root
                            rel = "package.json"
                        proof = f"{rel} -> {name}"
                        break
                if proof:
                    break
        if proof:
            profile.stacks.append(stack)
            profile.evidence[stack.name] = proof
    return profile
